#!/usr/bin/env bash

set -e

brew install tree-sitter-cli
brew install fd
brew install --cask font-symbols-only-nerd-font

defaults write NSGlobalDomain KeyRepeat -int 0
defaults write -g ApplePressAndHoldEnabled -bool false
defaults write com.apple.Finder AppleShowAllFiles -bool true
defaults write NSGlobalDomain AppleShowAllExtensions -bool true
defaults write com.apple.finder ShowStatusBar -bool true
defaults write com.apple.finder QLEnableTextSelection -bool true
