#!/bin/bash

# ohmyzsh
if [ ! -d ~/.oh-my-zsh ]; then
    # install oh my zsh
    echo "installing oh my zsh..."
    curl -L http://install.ohmyz.sh | sh
fi
 
# if we're on a mac...
if [ $(uname) == "Darwin" ]; then
    # run the osx script
    echo "running osx setup script" 
    ./scripts/osx
elif [ $(uname) == "Linux" ]; then
    echo "running linux setup script"
    ./scripts/linux
fi

./scripts/mv_dotfiles ./tilde
