#!/bin/bash

# if we're on a mac...
if [ $(uname) == "Darwin" ]; then
    # run the osx script
    echo "running osx setup script" 
    ./scripts/osx
elif [ $(uname) == "Linux" ]; then
    echo "running linux setup script"
    ./scripts/linux
fi

./scripts/mv_dotfiles ./tilde
