;;; mig-zenbones-light-theme.el --- Zenbones light theme -*- lexical-binding: t; -*-

;; This theme ports the default light Zenbones palette from:
;; https://github.com/mcchrish/zenbones.nvim
;; Zenbones source revision: 8304d8df9b823ff11e103afa62f38c39f534abe6
;; Lush source revision: 9c60ec2279d62487d942ce095e49006af28eed6e
;; Copyright (c) 2022 Michael Chris Lopez
;;
;; The MIT License (MIT)
;;
;; Permission is hereby granted, free of charge, to any person obtaining
;; a copy of this software and associated documentation files (the
;; "Software"), to deal in the Software without restriction, including
;; without limitation the rights to use, copy, modify, merge, publish,
;; distribute, sublicense, and/or sell copies of the Software, and to
;; permit persons to whom the Software is furnished to do so, subject to
;; the following conditions:
;;
;; The above copyright notice and this permission notice shall be
;; included in all copies or substantial portions of the Software.
;;
;; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
;; EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
;; MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
;; IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
;; CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
;; TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
;; SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

;;; Commentary:

;; A standalone port of the default Zenbones light palette for the workflows
;; retained by this Emacs configuration. Package faces inherit from stable core
;; faces wherever that keeps the theme small. Direct RGB colors are exact on
;; graphical and true-color terminals; lower-color terminals intentionally use
;; Emacs's nearest-color approximation instead of separate 256- and 16-color
;; specs.

;;; Code:

(deftheme mig-zenbones-light
  "A compact light theme derived from Zenbones.")

(let ((bg "#F0EDEC")
      (fg "#2C363C")
      (fg-match "#3E4B53")
      (fg-identifier "#44525B")
      (fg-special "#4F5E68")
      (fg-constant "#556570")
      (fg-secondary "#5E6F7B")
      (rose "#A8334C")
      (leaf "#4F6C31")
      (wood "#944927")
      (water "#286486")
      (blossom "#88507D")
      (sky "#3B8992")
      (bg1 "#CFC1BA")
      (rose1 "#94253E")
      (leaf1 "#3F5A22")
      (wood1 "#803D1C")
      (water1 "#1D5573")
      (blossom1 "#7B3B70")
      (sky1 "#2B747C")
      (comment "#948985")
      (line-number "#A4968F")
      (non-text "#BBABA3")
      (delimiter "#8E817B")
      (type "#6A5549")
      (cursor-line "#E9E4E2")
      (color-column "#E6C5BD")
      (float-bg "#DDD6D3")
      (float-border "#786D68")
      (popup-bg "#DAD3CF")
      (popup-selection "#C4B6AF")
      (popup-scrollbar "#B2A39B")
      (popup-thumb "#F7F6F5")
      (selection "#CBD9E3")
      (search "#DEB9D6")
      (active-search "#C074B2")
      (mode-line "#D6CDC9")
      (mode-line-inactive-bg "#E1DCD9")
      (mode-line-inactive-fg "#596A76")
      (inlay-fg "#A38C80")
      (inlay-bg "#EBE7E6")
      (spell-fg "#974352")
      (diff-add-bg "#CBE5B8")
      (diff-change-bg "#D4DEE7")
      (diff-delete-bg "#EBD8DA")
      (diff-text-bg "#A9BED1"))
  (custom-theme-set-faces
   'mig-zenbones-light

 ;; Core and syntax.
 `(default ((t (:background ,bg :foreground ,fg))))
 '(fixed-pitch ((t (:inherit default))))
 '(bold ((t (:weight bold))))
 '(bold-italic ((t (:inherit (bold italic)))))
 '(italic ((t (:slant italic))))
 `(cursor ((t (:background ,fg :foreground ,bg))))
 `(fringe ((t (:inherit default :foreground ,line-number))))
 `(region ((t (:background ,selection :foreground ,fg :extend t))))
 `(highlight ((t (:background ,cursor-line :extend t))))
 `(secondary-selection ((t (:background ,diff-change-bg :extend t))))
 `(shadow ((t (:foreground ,comment))))
 '(eglot-inlay-hint-face ((t (:inherit shadow :height 1.0))))
 `(minibuffer-prompt ((t (:foreground ,fg :weight bold))))
 `(tooltip ((t (:background ,float-bg :foreground ,fg))))
 `(child-frame-border ((t (:background ,float-border))))
 `(scroll-bar ((t (:foreground ,popup-thumb :background ,popup-scrollbar))))
 `(link ((t (:foreground ,sky :underline t))))
 `(link-visited ((t (:foreground ,blossom1 :underline t))))
 `(error ((t (:foreground ,rose))))
 `(warning ((t (:foreground ,wood))))
 `(success ((t (:foreground ,leaf))))
 `(escape-glyph ((t (:foreground ,fg-special :weight bold))))
 `(homoglyph ((t (:foreground ,fg-special :weight bold))))
 `(nobreak-space ((t (:foreground ,fg-special :weight bold))))
 `(trailing-whitespace ((t (:background ,rose))))
 `(vertical-border ((t (:foreground ,line-number))))
 `(window-divider ((t (:foreground ,line-number))))
 `(window-divider-first-pixel ((t (:foreground ,line-number))))
 `(window-divider-last-pixel ((t (:foreground ,line-number))))
 `(match ((t (:background ,search :foreground ,fg))))
 `(lazy-highlight ((t (:background ,search :foreground ,fg))))
 `(isearch ((t (:background ,active-search :foreground ,bg :weight bold))))
 `(isearch-fail ((t (:background ,rose :foreground ,bg :weight bold))))
 `(show-paren-match ((t (:background ,search :foreground ,fg))))
 `(show-paren-mismatch ((t (:background ,rose :foreground ,bg :weight bold))))
 `(font-lock-builtin-face ((t (:foreground ,fg-special :weight bold))))
 `(font-lock-comment-face ((t (:foreground ,comment :slant italic))))
 `(font-lock-comment-delimiter-face ((t (:foreground ,comment :slant italic))))
 `(font-lock-doc-face ((t (:foreground ,comment :slant italic))))
 `(font-lock-constant-face ((t (:foreground ,fg-constant :slant italic))))
 `(font-lock-function-name-face ((t (:foreground ,fg))))
 `(font-lock-function-call-face ((t (:foreground ,fg))))
 `(font-lock-keyword-face ((t (:foreground ,fg :weight bold))))
 `(font-lock-number-face ((t (:foreground ,fg-constant :slant normal))))
 `(font-lock-preprocessor-face ((t (:foreground ,fg :weight bold))))
 `(font-lock-string-face ((t (:foreground ,fg-constant :slant italic))))
 `(font-lock-regexp-face ((t (:foreground ,fg-constant :slant italic))))
 `(font-lock-type-face ((t (:foreground ,type))))
 `(font-lock-variable-name-face ((t (:foreground ,fg-identifier))))
 `(font-lock-variable-use-face ((t (:foreground ,fg-identifier))))
 `(font-lock-property-name-face ((t (:foreground ,fg-identifier))))
 `(font-lock-property-use-face ((t (:foreground ,fg-identifier))))
 `(font-lock-operator-face ((t (:foreground ,fg :weight bold))))
 `(font-lock-negation-char-face ((t (:foreground ,fg :weight bold))))
 `(font-lock-escape-face ((t (:foreground ,fg-special :weight bold))))
 `(font-lock-doc-markup-face ((t (:foreground ,fg-special :weight bold))))
 `(font-lock-bracket-face ((t (:foreground ,delimiter))))
 `(font-lock-delimiter-face ((t (:foreground ,delimiter))))
 `(font-lock-misc-punctuation-face ((t (:foreground ,delimiter))))
 `(font-lock-punctuation-face ((t (:foreground ,delimiter))))
 `(font-lock-regexp-grouping-backslash ((t (:foreground ,fg-special :weight bold))))
 `(font-lock-regexp-grouping-construct ((t (:foreground ,fg-special :weight bold))))
 '(font-lock-warning-face ((t (:inherit warning))))

 ;; Tree-sitter and fallback programming modes.
 '(typescript-ts-jsx-tag-face ((t (:inherit font-lock-builtin-face))))
 '(typescript-ts-jsx-attribute-face
   ((t (:inherit font-lock-property-name-face))))
 '(nim-font-lock-export-face ((t (:inherit font-lock-builtin-face))))
 '(nim-font-lock-pragma-face ((t (:inherit font-lock-preprocessor-face))))
 '(nim-non-overloadable-face ((t (:inherit font-lock-builtin-face))))
 '(nim-font-lock-number-face ((t (:inherit font-lock-number-face))))
 '(zig-multiline-string-face ((t (:inherit font-lock-string-face))))
 '(php-string ((t (:inherit font-lock-string-face))))
 '(php-keyword ((t (:inherit font-lock-keyword-face))))
 '(php-class-declaration ((t (:inherit font-lock-keyword-face))))
 '(php-class-declaration-spec ((t (:inherit font-lock-keyword-face))))
 '(php-namespace-declaration ((t (:inherit font-lock-keyword-face))))
 '(php-import-declaration ((t (:inherit font-lock-keyword-face))))
 '(php-class-modifier ((t (:inherit font-lock-keyword-face))))
 '(php-method-modifier ((t (:inherit font-lock-keyword-face))))
 '(php-visibility-modifier ((t (:inherit font-lock-keyword-face))))
 '(php-control-structure ((t (:inherit font-lock-keyword-face))))
 '(php-builtin ((t (:inherit font-lock-builtin-face))))
 '(php-magical-constant ((t (:inherit font-lock-builtin-face))))
 '(php-function-name ((t (:inherit font-lock-function-name-face))))
 '(php-function-call-standard ((t (:inherit font-lock-function-call-face))))
 '(php-function-call-traditional
   ((t (:inherit font-lock-function-call-face))))
 '(php-method-call-standard ((t (:inherit font-lock-function-call-face))))
 '(php-method-call-traditional ((t (:inherit font-lock-function-call-face))))
 '(php-static-method-call-standard
   ((t (:inherit font-lock-function-call-face))))
 '(php-static-method-call-traditional
   ((t (:inherit font-lock-function-call-face))))
 '(php-variable-name ((t (:inherit font-lock-variable-name-face))))
 '(php-property-name ((t (:inherit font-lock-property-name-face))))
 '(php-type ((t (:inherit font-lock-type-face))))
 '(php-class ((t (:inherit font-lock-type-face))))
 '(php-doc-$this ((t (:inherit font-lock-type-face))))
 '(php-doc-class-name ((t (:inherit font-lock-type-face))))
 '(php-constant ((t (:inherit font-lock-constant-face))))
 '(php-constant-assign ((t (:inherit font-lock-constant-face))))
 '(php-this ((t (:inherit font-lock-constant-face))))
 '(php-php-tag ((t (:inherit font-lock-preprocessor-face))))
 '(php-doc-annotation-tag ((t (:inherit font-lock-doc-markup-face))))
 `(php-doc-variable-sigil ((t (:foreground ,delimiter))))
 `(php-variable-sigil ((t (:foreground ,delimiter))))
 `(php-this-sigil ((t (:foreground ,delimiter))))
 `(php-doc-$this-sigil ((t (:foreground ,delimiter))))
 '(php-operator ((t (:inherit font-lock-operator-face))))
 '(php-assignment-op ((t (:inherit font-lock-operator-face))))
 '(php-comparison-op ((t (:inherit font-lock-operator-face))))
 '(php-logical-op ((t (:inherit font-lock-operator-face))))
 '(php-arithmetic-op ((t (:inherit font-lock-operator-face))))
 '(php-inc-dec-op ((t (:inherit font-lock-operator-face))))
 '(php-string-op ((t (:inherit font-lock-operator-face))))
 '(php-object-op ((t (:inherit font-lock-operator-face))))
 '(php-pipe-op ((t (:inherit font-lock-operator-face))))
 '(php-paamayim-nekudotayim ((t (:inherit font-lock-operator-face))))
 '(php-errorcontrol-op ((t (:inherit font-lock-operator-face))))
 '(css-proprietary-property ((t (:inherit warning))))
 `(css-property ((t (:foreground ,fg-identifier))))
 `(css-selector ((t (:foreground ,fg :weight bold))))
 `(line-number ((t (:foreground ,line-number :weight normal :underline nil
                   :strike-through nil))))
 `(line-number-current-line
   ((t (:foreground ,fg :weight bold :underline nil :strike-through nil))))
 `(hl-line ((t (:background ,cursor-line :extend t))))
 `(whitespace-big-indent ((t (:foreground ,non-text))))
 `(whitespace-hspace ((t (:foreground ,non-text))))
 `(whitespace-indentation ((t (:foreground ,non-text))))
 `(whitespace-newline ((t (:foreground ,non-text))))
 `(whitespace-page-delimiter ((t (:foreground ,non-text))))
 `(whitespace-space ((t (:foreground ,non-text))))
 `(whitespace-space-after-tab ((t (:foreground ,non-text))))
 `(whitespace-space-before-tab ((t (:foreground ,non-text))))
 `(whitespace-tab ((t (:foreground ,non-text))))
 `(whitespace-empty ((t (:foreground ,rose :background ,diff-delete-bg))))
 `(whitespace-missing-newline-at-eof
   ((t (:foreground ,rose :background ,diff-delete-bg))))
 `(whitespace-trailing ((t (:foreground ,rose :background ,diff-delete-bg))))

 ;; Selection and frame chrome.
 '(icomplete-first-match ((t (:foreground "#4078f2" :weight bold))))
 '(icomplete-selected-match ((t (:background "#dfdfdf" :foreground "#383a42"))))
 '(completions-common-part ((t (:foreground "#4078f2" :weight bold))))
 '(completions-first-difference ((t (:foreground "#e45649"))))
 '(xref-file-header ((t (:inherit success))))
 '(xref-line-number ((t (:foreground "#4078f2"))))
 '(xref-match ((t (:background "#f0f0f0" :foreground "#50a14f" :weight bold))))
 `(mode-line ((t (:background ,mode-line :foreground ,fg))))
 `(mode-line-active ((t (:background ,mode-line :foreground ,fg))))
 `(mode-line-inactive
   ((t (:background ,mode-line-inactive-bg :foreground ,mode-line-inactive-fg))))
 `(mode-line-emphasis ((t (:foreground ,fg :weight bold))))
 '(mode-line-highlight ((t (:inherit highlight))))
 `(mode-line-buffer-id ((t (:foreground ,fg :weight bold))))
 '(header-line ((t (:inherit mode-line))))
 `(tab-bar ((t (:background ,mode-line-inactive-bg
                :foreground ,mode-line-inactive-fg))))
 `(tab-bar-tab ((t (:background ,mode-line :foreground ,fg :weight bold))))
 `(tab-bar-tab-inactive
   ((t (:background ,mode-line-inactive-bg :foreground ,mode-line-inactive-fg))))
 '(tab-bar-tab-group-current ((t (:inherit tab-bar-tab))))
 '(tab-bar-tab-group-inactive ((t (:inherit tab-bar-tab-inactive))))
 '(tab-bar-tab-ungrouped ((t (:inherit tab-bar-tab))))
 '(tab-bar-tab-highlight ((t (:inherit highlight))))

 ;; Terminal, compilation, diagnostics, and diffs.
 `(ansi-color-black ((t (:foreground ,bg :background ,bg))))
 `(ansi-color-red ((t (:foreground ,rose :background ,rose))))
 `(ansi-color-green ((t (:foreground ,leaf :background ,leaf))))
 `(ansi-color-yellow ((t (:foreground ,wood :background ,wood))))
 `(ansi-color-blue ((t (:foreground ,water :background ,water))))
 `(ansi-color-magenta ((t (:foreground ,blossom :background ,blossom))))
 `(ansi-color-cyan ((t (:foreground ,sky :background ,sky))))
 `(ansi-color-white ((t (:foreground ,fg :background ,fg))))
 `(ansi-color-bright-black ((t (:foreground ,bg1 :background ,bg1))))
 `(ansi-color-bright-red ((t (:foreground ,rose1 :background ,rose1))))
 `(ansi-color-bright-green ((t (:foreground ,leaf1 :background ,leaf1))))
 `(ansi-color-bright-yellow ((t (:foreground ,wood1 :background ,wood1))))
 `(ansi-color-bright-blue ((t (:foreground ,water1 :background ,water1))))
 `(ansi-color-bright-magenta
   ((t (:foreground ,blossom1 :background ,blossom1))))
 `(ansi-color-bright-cyan ((t (:foreground ,sky1 :background ,sky1))))
 `(ansi-color-bright-white ((t (:foreground ,fg-special :background ,fg-special))))
 '(compilation-column-number ((t (:inherit font-lock-comment-face))))
 '(compilation-line-number ((t (:foreground "#4078f2"))))
 '(compilation-error ((t (:inherit error :weight bold))))
 '(compilation-warning ((t (:inherit warning :slant italic))))
 '(compilation-info ((t (:inherit success))))
 '(flymake-error ((t (:underline (:style wave :color "#e45649")))))
 '(flymake-note ((t (:underline (:style wave :color "#50a14f")))))
 '(flymake-warning ((t (:underline (:style wave :color "#da8548")))))
 '(flyspell-incorrect ((t (:underline (:style wave :color "#e45649")))))
 '(flyspell-duplicate ((t (:underline (:style wave :color "#986801")))))
 '(diff-added ((t (:background "#eef7ee" :foreground "#50a14f" :extend t))))
 '(diff-changed ((t (:foreground "#b751b6"))))
 '(diff-context ((t (:foreground "#6f7377"))))
 '(diff-removed ((t (:background "#f7e2e0" :foreground "#e45649" :extend t))))
 '(diff-header ((t (:foreground "#0184bc"))))
 '(diff-file-header ((t (:foreground "#4078f2" :weight bold))))
 '(diff-hunk-header ((t (:foreground "#b751b6"))))

 ;; Files and prose.
 '(dired-directory ((t (:foreground "#a626a4"))))
 '(dired-ignored ((t (:foreground "#9ca0a4"))))
 '(dired-flagged ((t (:foreground "#e45649"))))
 '(dired-header ((t (:foreground "#4078f2" :weight bold))))
 '(dired-mark ((t (:foreground "#da8548" :weight bold))))
 '(dired-marked ((t (:foreground "#a626a4" :weight bold :inverse-video t))))
 '(dired-perm-write ((t (:foreground "#383a42" :underline t))))
 '(dired-symlink ((t (:foreground "#0184bc" :weight bold))))
 ;; Markdown, GFM, and Markdown Tree-sitter.
 `(markdown-header-face ((t (:foreground ,fg :weight bold))))
 `(markdown-header-face-1 ((t (:foreground ,fg :weight bold))))
 `(markdown-header-face-2 ((t (:foreground ,fg :weight bold))))
 `(markdown-header-face-3 ((t (:foreground ,fg :weight bold))))
 `(markdown-header-face-4 ((t (:foreground ,fg :weight bold))))
 `(markdown-header-face-5 ((t (:foreground ,fg :weight bold))))
 `(markdown-header-face-6 ((t (:foreground ,fg :weight bold))))
 `(markdown-header-rule-face ((t (:foreground ,delimiter))))
 `(markdown-header-delimiter-face ((t (:foreground ,delimiter))))
 `(markdown-markup-face ((t (:foreground ,delimiter))))
 `(markdown-line-break-face ((t (:foreground ,delimiter))))
 `(markdown-hr-face ((t (:foreground ,delimiter))))
 `(markdown-html-tag-delimiter-face ((t (:foreground ,delimiter))))
 '(markdown-bold-face ((t (:inherit bold))))
 '(markdown-italic-face ((t (:inherit italic))))
 '(markdown-strike-through-face ((t (:strike-through t))))
 `(markdown-list-face ((t (:foreground ,fg-special :weight bold))))
 `(markdown-gfm-checkbox-face ((t (:foreground ,fg-special :weight bold))))
 `(markdown-math-face ((t (:foreground ,fg-special :weight bold))))
 `(markdown-html-entity-face ((t (:foreground ,fg-special :weight bold))))
 `(markdown-blockquote-face ((t (:foreground ,fg-constant :slant italic))))
 `(markdown-code-face
   ((t (:inherit fixed-pitch :foreground ,type :background ,inlay-bg :extend t))))
 `(markdown-pre-face
   ((t (:inherit fixed-pitch :foreground ,type :background ,inlay-bg :extend t))))
 '(markdown-inline-code-face
   ((t (:inherit (markdown-code-face markdown-pre-face) :extend nil :height 1.0))))
 `(markdown-table-face ((t (:foreground ,fg))))
 `(markdown-language-keyword-face ((t (:foreground ,fg :weight bold))))
 `(markdown-language-info-face ((t (:foreground ,fg-secondary :slant italic))))
 `(markdown-link-face ((t (:foreground ,fg-identifier :underline t))))
 `(markdown-url-face ((t (:foreground ,comment :underline t))))
 `(markdown-plain-url-face ((t (:foreground ,comment :underline t))))
 '(markdown-missing-link-face ((t (:inherit error))))
 `(markdown-reference-face ((t (:foreground ,fg-constant))))
 `(markdown-footnote-text-face ((t (:foreground ,fg-constant))))
 `(markdown-footnote-marker-face ((t (:foreground ,fg-special :weight bold))))
 `(markdown-link-title-face ((t (:foreground ,fg-constant :slant italic))))
 '(markdown-comment-face ((t (:inherit font-lock-comment-face))))
 `(markdown-metadata-key-face ((t (:foreground ,fg :weight bold))))
 `(markdown-metadata-value-face ((t (:foreground ,fg-constant :slant italic))))
 '(markdown-highlight-face ((t (:inherit highlight))))
 '(markdown-highlighting-face ((t (:inherit highlight))))
 `(markdown-html-tag-name-face ((t (:foreground ,fg-special :weight bold))))
 `(markdown-html-attr-name-face ((t (:foreground ,fg-identifier))))
 '(markdown-html-attr-value-face ((t (:inherit font-lock-string-face))))
 `(markdown-ts-heading-1 ((t (:foreground ,fg :weight bold))))
 `(markdown-ts-heading-2 ((t (:foreground ,fg :weight bold))))
 `(markdown-ts-heading-3 ((t (:foreground ,fg :weight bold))))
 `(markdown-ts-heading-4 ((t (:foreground ,fg :weight bold))))
 `(markdown-ts-heading-5 ((t (:foreground ,fg :weight bold))))
 `(markdown-ts-heading-6 ((t (:foreground ,fg :weight bold))))
 `(markdown-ts-setext-heading ((t (:foreground ,fg :weight bold))))
 `(markdown-ts-delimiter ((t (:foreground ,delimiter))))
 `(markdown-ts-table-delimiter-cell ((t (:foreground ,delimiter))))
 `(markdown-ts-hard-line-break-backslash ((t (:foreground ,delimiter))))
 `(markdown-ts-hard-line-break-backslash-hidden ((t (:foreground ,delimiter))))
 `(markdown-ts-hard-line-break-space ((t (:foreground ,delimiter))))
 `(markdown-ts-hard-line-break-space-hidden ((t (:foreground ,delimiter))))
 `(markdown-ts-thematic-break ((t (:foreground ,delimiter))))
 '(markdown-ts-bold ((t (:weight bold))))
 '(markdown-ts-emphasis ((t (:slant italic))))
 '(markdown-ts-strikethrough ((t (:strike-through t))))
 `(markdown-ts-link ((t (:foreground ,fg-identifier :underline t))))
 `(markdown-ts-link-destination ((t (:foreground ,comment :underline t))))
 `(markdown-ts-block-quote ((t (:foreground ,fg-constant :slant italic))))
 `(markdown-ts-code-block
   ((t (:inherit fixed-pitch :foreground ,type :background ,inlay-bg :extend t))))
 `(markdown-ts-indented-code-block
   ((t (:inherit fixed-pitch :foreground ,type :background ,inlay-bg :extend t))))
 `(markdown-ts-in-code-block
   ((t (:inherit fixed-pitch :foreground ,type :background ,inlay-bg :extend t))))
 '(markdown-ts-code-span
   ((t (:inherit (markdown-ts-code-block font-lock-constant-face)
        :extend nil :height 1.0))))
 `(markdown-ts-code-block-markup-hidden ((t (:background ,inlay-bg))))
 `(markdown-ts-language-keyword ((t (:foreground ,fg :weight bold))))
 `(markdown-ts-list-marker ((t (:foreground ,fg-special :weight bold))))
 `(markdown-ts-task-checked ((t (:foreground ,fg-special :weight bold))))
 `(markdown-ts-task-unchecked ((t (:foreground ,fg-special :weight bold))))
 `(markdown-ts-entity-reference ((t (:foreground ,fg-special :weight normal))))
 `(markdown-ts-numeric-character-reference
   ((t (:foreground ,fg-special :weight normal))))
 `(markdown-ts-latex ((t (:foreground ,fg-special :weight normal))))
 `(markdown-ts-html-tag ((t (:foreground ,fg-special :weight normal))))
 '(markdown-ts-html-block ((t (:inherit default))))
 `(markdown-ts-table ((t (:foreground ,fg))))
 `(markdown-ts-table-cell ((t (:foreground ,fg))))
 `(markdown-ts-in-table ((t (:foreground ,fg))))
 `(markdown-ts-table-header ((t (:foreground ,fg :weight bold))))

 ;; Org, Agenda, citations, and research packages.
 '(org-default ((t (:inherit default))))
 `(org-document-title ((t (:foreground ,fg :weight bold))))
 `(org-document-info ((t (:foreground ,fg))))
 `(org-document-info-keyword ((t (:foreground ,comment))))
 `(org-meta-line ((t (:foreground ,comment))))
 `(org-drawer ((t (:foreground ,comment))))
 `(org-archived ((t (:foreground ,comment))))
 `(org-special-keyword ((t (:foreground ,comment))))
 `(org-level-1 ((t (:foreground ,fg :weight bold))))
 `(org-level-2 ((t (:foreground ,fg :weight bold))))
 `(org-level-3 ((t (:foreground ,fg :weight bold))))
 `(org-level-4 ((t (:foreground ,fg :weight bold))))
 `(org-level-5 ((t (:foreground ,fg :weight bold))))
 `(org-level-6 ((t (:foreground ,fg :weight bold))))
 `(org-level-7 ((t (:foreground ,fg :weight bold))))
 `(org-level-8 ((t (:foreground ,fg :weight bold))))
 `(outline-1 ((t (:foreground ,fg :weight bold))))
 `(outline-2 ((t (:foreground ,fg :weight bold))))
 `(outline-3 ((t (:foreground ,fg :weight bold))))
 `(outline-4 ((t (:foreground ,fg :weight bold))))
 `(outline-5 ((t (:foreground ,fg :weight bold))))
 `(outline-6 ((t (:foreground ,fg :weight bold))))
 `(outline-7 ((t (:foreground ,fg :weight bold))))
 `(outline-8 ((t (:foreground ,fg :weight bold))))
 `(org-block ((t (:background ,inlay-bg :extend t))))
 `(org-inline-src-block ((t (:background ,inlay-bg :extend t))))
 `(org-block-begin-line
   ((t (:foreground ,comment :background ,inlay-bg :slant italic :extend t))))
 `(org-block-end-line
   ((t (:foreground ,comment :background ,inlay-bg :slant italic :extend t))))
 `(org-code ((t (:foreground ,type))))
 `(org-verbatim ((t (:foreground ,type))))
 `(org-latex-and-related ((t (:foreground ,type))))
 `(org-formula ((t (:foreground ,type))))
 `(org-macro ((t (:foreground ,type))))
 `(org-quote
   ((t (:foreground ,fg-constant :background ,inlay-bg :slant italic :extend t))))
 `(org-verse
   ((t (:foreground ,fg-constant :background ,inlay-bg :slant italic :extend t))))
 `(org-link ((t (:foreground ,fg-identifier :underline t))))
 `(org-target ((t (:foreground ,fg-identifier :underline t))))
 `(org-footnote ((t (:foreground ,fg-special))))
 `(org-table ((t (:foreground ,fg))))
 `(org-table-row ((t (:foreground ,fg))))
 `(org-table-header ((t (:foreground ,fg :weight bold))))
 `(org-list-dt ((t (:foreground ,fg-special :weight bold))))
 `(org-property-value ((t (:foreground ,fg-constant))))
 `(org-tag ((t (:foreground ,comment :weight normal))))
 `(org-tag-group ((t (:foreground ,comment :weight normal))))
 `(org-priority ((t (:foreground ,rose))))
 `(org-warning ((t (:foreground ,rose))))
 `(org-imminent-deadline ((t (:foreground ,rose))))
 `(org-hide ((t (:foreground ,bg))))
 `(org-ellipsis ((t (:foreground ,delimiter :background ,bg :underline nil))))
 `(org-checkbox ((t (:foreground ,fg-special :weight bold))))
 `(org-checkbox-statistics-done ((t (:foreground ,leaf))))
 `(org-checkbox-statistics-todo ((t (:foreground ,wood))))
 `(org-clock-overlay ((t (:background ,selection))))
 `(org-column ((t (:background ,float-bg))))
 `(org-column-title ((t (:foreground ,fg :background ,float-bg :weight bold))))
 `(org-dispatcher-highlight
   ((t (:foreground ,bg :background ,blossom :weight bold))))
 '(org-mode-line-clock ((t (:inherit mode-line))))
 `(org-mode-line-clock-overrun ((t (:inherit mode-line :foreground ,rose))))
 `(org-todo ((t (:foreground ,fg :weight bold :underline t))))
 `(org-done ((t (:foreground ,leaf))))
 `(org-headline-done ((t (:foreground ,leaf))))
 '(org-headline-todo ((t (:inherit org-todo))))
 `(org-date ((t (:foreground ,wood))))
 `(org-date-selected ((t (:foreground ,wood :background ,selection))))
 `(org-sexp-date ((t (:foreground ,wood))))
 `(org-scheduled ((t (:foreground ,wood))))
 `(org-scheduled-today ((t (:foreground ,wood :weight bold))))
 `(org-scheduled-previously ((t (:foreground ,rose))))
 `(org-upcoming-deadline ((t (:foreground ,wood))))
 `(org-upcoming-distant-deadline ((t (:foreground ,comment))))
 `(org-agenda-structure ((t (:foreground ,fg :weight bold))))
 `(org-agenda-structure-filter ((t (:foreground ,fg :weight bold))))
 `(org-agenda-structure-secondary ((t (:foreground ,fg :weight bold))))
 `(org-agenda-date ((t (:foreground ,fg))))
 `(org-agenda-date-weekend ((t (:foreground ,comment))))
 `(org-agenda-date-today ((t (:foreground ,fg :weight bold :underline t))))
 `(org-agenda-date-weekend-today
   ((t (:foreground ,fg :weight bold :underline t))))
 `(org-agenda-current-time ((t (:foreground ,water :weight bold))))
 `(org-agenda-done ((t (:foreground ,leaf))))
 `(org-agenda-dimmed-todo-face ((t (:foreground ,comment))))
 `(org-agenda-clocking ((t (:background ,selection))))
 `(org-agenda-restriction-lock ((t (:background ,search))))
 `(org-agenda-filter-category ((t (:foreground ,blossom :weight bold))))
 `(org-agenda-filter-effort ((t (:foreground ,blossom :weight bold))))
 `(org-agenda-filter-regexp ((t (:foreground ,blossom :weight bold))))
 `(org-agenda-filter-tags ((t (:foreground ,blossom :weight bold))))
 '(org-agenda-calendar-daterange ((t (:inherit org-date))))
 '(org-agenda-calendar-event ((t (:inherit default))))
 '(org-agenda-calendar-sexp ((t (:inherit default))))
 `(org-agenda-column-dateline
   ((t (:inherit org-column :foreground ,line-number))))
 '(org-agenda-diary ((t (:inherit default))))
 `(org-time-grid ((t (:foreground ,line-number))))
 `(org-cite ((t (:foreground ,sky :underline t))))
 `(org-cite-key ((t (:foreground ,fg-identifier :underline t))))
 `(org-ref-ref-face ((t (:foreground ,sky :underline t))))
 `(org-ref-label-face ((t (:foreground ,fg-identifier :underline t))))
 `(org-ref-cite-face ((t (:foreground ,wood :underline t))))
 `(org-ref-glossary-face ((t (:foreground ,blossom))))
 `(org-ref-acronym-face ((t (:foreground ,fg-special))))
 '(org-ref-bad-cite-key-face ((t (:inherit error))))
 '(org-ref-cite-invalid-local-prefix/suffix-face ((t (:inherit error))))
 `(org-ref-cite-global-prefix/suffix-face ((t (:foreground ,comment))))
 `(org-ref-cite-&-face ((t (:foreground ,comment))))
 `(org-ref-cite-local-prefix/suffix-face ((t (:foreground ,comment))))
 '(org-roam-header-line ((t (:inherit header-line))))
 `(org-roam-title ((t (:foreground ,fg :weight bold))))
 `(org-roam-preview-heading ((t (:foreground ,fg :weight bold))))
 `(org-roam-olp ((t (:foreground ,comment))))
 `(org-roam-dim ((t (:foreground ,comment))))
 `(org-roam-preview-heading-highlight ((t (:background ,cursor-line :weight bold))))
 `(org-roam-preview-heading-selection ((t (:background ,selection :weight bold))))
 `(org-roam-preview-region ((t (:background ,cursor-line :extend t))))
 `(org-roam-overlay ((t (:background ,cursor-line :extend t))))
 `(org-roam-dailies-calendar-note ((t (:foreground ,sky :weight bold))))
 `(gscholar-bibtex-title ((t (:foreground ,fg :weight bold :height 1.4))))
 `(gscholar-bibtex-subtitle ((t (:foreground ,comment :height 1.0))))

 ;; Magit keeps its current semantic colors with fixed pale backgrounds.
 '(magit-branch-current ((t (:foreground "#4078f2" :weight bold))))
 '(magit-branch-local ((t (:foreground "#0184bc"))))
 '(magit-branch-remote ((t (:foreground "#50a14f"))))
 '(magit-diff-added ((t (:background "#e9f1e8" :foreground "#40803f" :extend t))))
 '(magit-diff-added-highlight ((t (:background "#d8e8d7" :foreground "#50a14f" :weight bold :extend t))))
 '(magit-diff-base ((t (:background "#faeee6" :foreground "#ae6a39" :extend t))))
 '(magit-diff-base-highlight ((t (:background "#f6ddcc" :foreground "#da8548" :weight bold :extend t))))
 '(magit-diff-context ((t (:background "#fafafa" :foreground "#9ca0a4" :extend t))))
 '(magit-diff-context-highlight ((t (:background "#f0f0f0" :foreground "#383a42" :extend t))))
 '(magit-diff-file-heading ((t (:foreground "#383a42" :weight bold :extend t))))
 '(magit-diff-file-heading-selection ((t (:background "#a0bcf8" :foreground "#a626a4" :weight bold :extend t))))
 '(magit-diff-hunk-heading ((t (:background "#e5c7e5" :foreground "#fafafa" :extend t))))
 '(magit-diff-hunk-heading-highlight ((t (:background "#b751b6" :foreground "#fafafa" :weight bold :extend t))))
 '(magit-diff-removed ((t (:background "#f7e9e8" :foreground "#b6443a" :extend t))))
 '(magit-diff-removed-highlight ((t (:background "#f5d9d6" :foreground "#e45649" :weight bold :extend t))))
 '(magit-dimmed ((t (:foreground "#c6c7c7"))))
 '(magit-hash ((t (:foreground "#9ca0a4"))))
 '(magit-filename ((t (:foreground "#b751b6"))))
 '(magit-log-author ((t (:foreground "#da8548"))))
 '(magit-log-date ((t (:foreground "#4078f2"))))
 '(magit-log-graph ((t (:foreground "#9ca0a4"))))
 '(magit-process-ng ((t (:inherit error))))
 '(magit-process-ok ((t (:inherit success))))
 '(magit-section-heading ((t (:foreground "#4078f2" :weight bold :extend t))))
 '(magit-section-heading-selection ((t (:foreground "#da8548" :weight bold :extend t))))
 '(magit-section-highlight ((t (:inherit hl-line))))
 '(magit-section-secondary-heading ((t (:foreground "#b751b6" :weight bold :extend t))))
 '(magit-tag ((t (:foreground "#986801"))))

 ;; Retained UI packages.
 '(which-key-key-face ((t (:foreground "#50a14f"))))
 '(which-key-group-description-face ((t (:foreground "#b751b6"))))
 '(which-key-command-description-face ((t (:foreground "#4078f2"))))
 '(which-key-local-map-description-face ((t (:foreground "#a626a4"))))
 '(evil-ex-info ((t (:foreground "#e45649" :slant italic))))
 '(evil-ex-search ((t (:background "#4078f2" :foreground "#f0f0f0" :weight bold))))
 '(evil-ex-substitute-matches ((t (:background "#f0f0f0" :foreground "#e45649" :weight bold :strike-through t))))
 '(evil-ex-substitute-replacement ((t (:background "#f0f0f0" :foreground "#50a14f" :weight bold))))
 '(gptel-context-highlight-face ((t (:background "#e7e7e7" :foreground "#383a42"))))
 '(gptel-context-deletion-face ((t (:background "#f7e2e0" :foreground "#e45649" :strike-through t))))
 '(gptel-rewrite-highlight-face ((t (:background "#dce7fd" :foreground "#202328")))))

  (custom-theme-set-variables
   'mig-zenbones-light
   `(org-todo-keyword-faces
     '(("PROJ" :foreground ,water :weight bold)
       ("TODO" :foreground ,fg :weight bold :underline t)
       ("REVIEW" :foreground ,blossom :weight bold)
       ("POST" :foreground ,sky :weight bold)
       ("DOING" :foreground ,wood :weight bold)
       ("BLOCKED" :foreground ,rose :weight bold)
       ("DONE" :foreground ,leaf :weight bold)
       ("CANCELED" :foreground ,comment :strike-through t))))
)

(custom-theme-set-variables
 'mig-zenbones-light
 '(frame-background-mode 'light))

(provide-theme 'mig-zenbones-light)

;;; mig-zenbones-light-theme.el ends here
