;;; appearance-test.el --- Appearance behavior tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'face-remap)
(require 'markdown-ts-mode)

(load (expand-file-name "init.el" (file-name-directory (or load-file-name buffer-file-name)))
      nil nil nil t)

(defconst my/appearance-font-lock-attributes
  '((font-lock-builtin-face :foreground "#4F5E68" :weight bold)
    (font-lock-comment-face :foreground "#948985" :slant italic)
    (font-lock-comment-delimiter-face :foreground "#948985" :slant italic)
    (font-lock-doc-face :foreground "#948985" :slant italic)
    (font-lock-constant-face :foreground "#556570" :slant italic)
    (font-lock-function-name-face :foreground "#2C363C")
    (font-lock-function-call-face :foreground "#2C363C")
    (font-lock-keyword-face :foreground "#2C363C" :weight bold)
    (font-lock-number-face :foreground "#556570" :slant normal)
    (font-lock-preprocessor-face :foreground "#2C363C" :weight bold)
    (font-lock-string-face :foreground "#556570" :slant italic)
    (font-lock-regexp-face :foreground "#556570" :slant italic)
    (font-lock-type-face :foreground "#6A5549")
    (font-lock-variable-name-face :foreground "#44525B")
    (font-lock-variable-use-face :foreground "#44525B")
    (font-lock-property-name-face :foreground "#44525B")
    (font-lock-property-use-face :foreground "#44525B")
    (font-lock-operator-face :foreground "#2C363C" :weight bold)
    (font-lock-negation-char-face :foreground "#2C363C" :weight bold)
    (font-lock-escape-face :foreground "#4F5E68" :weight bold)
    (font-lock-doc-markup-face :foreground "#4F5E68" :weight bold)
    (font-lock-bracket-face :foreground "#8E817B")
    (font-lock-delimiter-face :foreground "#8E817B")
    (font-lock-misc-punctuation-face :foreground "#8E817B")
    (font-lock-punctuation-face :foreground "#8E817B")
    (font-lock-regexp-grouping-backslash :foreground "#4F5E68" :weight bold)
    (font-lock-regexp-grouping-construct :foreground "#4F5E68" :weight bold)
    (font-lock-warning-face :foreground "#944927")
    (typescript-ts-jsx-tag-face :foreground "#4F5E68" :weight bold)
    (typescript-ts-jsx-attribute-face :foreground "#44525B" :slant normal)))

(defconst my/appearance-markdown-ts-attributes
  '((markdown-ts-heading-1 :foreground "#2C363C" :weight bold)
    (markdown-ts-delimiter :foreground "#8E817B")
    (markdown-ts-emphasis :slant italic)
    (markdown-ts-block-quote :foreground "#556570" :slant italic)
    (markdown-ts-list-marker :foreground "#4F5E68" :weight bold)
    (markdown-ts-task-checked :foreground "#4F5E68" :weight bold)
    (markdown-ts-link :foreground "#44525B" :underline t)
    (markdown-ts-link-destination :foreground "#948985" :underline t)
    (markdown-ts-table :foreground "#2C363C")
    (markdown-ts-table-header :foreground "#2C363C" :weight bold)
    (markdown-ts-table-cell :foreground "#2C363C")
    (markdown-ts-table-delimiter-cell :foreground "#8E817B")
    (markdown-ts-language-keyword :foreground "#2C363C" :weight bold)
    (markdown-ts-code-span :foreground "#6A5549" :background "#EBE7E6"
                           :height 1.0 :extend nil)
    (markdown-ts-code-block :foreground "#6A5549" :background "#EBE7E6"
                            :extend t)))

(defun my/appearance-load-theme ()
  "Enable the configured appearance theme before inspecting effective faces."
  (load-theme 'mig-zenbones-light t))

(defun my/appearance-assert-face-attributes (face attributes)
  "Assert that FACE resolves ATTRIBUTES through its active inheritance chain."
  (let ((remaining attributes))
    (while remaining
      (let ((attribute (pop remaining))
            (expected (pop remaining)))
        (let ((actual (face-attribute face attribute nil t)))
          (if (and (numberp actual) (numberp expected))
              (should (= actual expected))
            (should (equal actual expected))))))))

(defun my/appearance-assert-rendered-faces (attributes)
  "Assert every fontified face in the current buffer has an exact known role."
  (let ((position (point-min)))
    (while (< position (point-max))
      (let ((next (next-single-property-change position 'face nil (point-max)))
            (rendered (get-text-property position 'face)))
        (dolist (face (if (listp rendered) rendered (list rendered)))
          (when face
            (let ((expected (assq face attributes)))
              (should expected)
              (my/appearance-assert-face-attributes face (cdr expected)))))
        (setq position next)))))

(defun my/appearance-assert-tokens (tokens attributes)
  "Assert TOKENS carry their semantic faces and exact effective ATTRIBUTES."
  (goto-char (point-min))
  (dolist (token tokens)
    (let ((text (nth 0 token))
          (expected-face (nth 1 token)))
      (should (search-forward text nil t))
      (let ((rendered (get-text-property (match-beginning 0) 'face))
            (expected (assq expected-face attributes)))
        (should (memq expected-face
                      (if (listp rendered) rendered (list rendered))))
        (should expected)
        (my/appearance-assert-face-attributes expected-face (cdr expected))))))

(defun my/appearance-verify-tree-sitter-tokens ()
  "Verify level-four Tree-sitter fontification for every configured mode."
  (should (= treesit-font-lock-level 4))
  (dolist
      (spec
       '((c-ts-mode
          "#define C_MACRO 7\n// c-comment\nstruct CItem { int c_field; };\nint c_call(struct CItem c_item) { int c_number = 8; return c_call(c_item) + c_item.c_field; }\n"
          (("#define" font-lock-preprocessor-face)
           ("c-comment" font-lock-comment-face)
           ("struct" font-lock-keyword-face)
           ("CItem" font-lock-type-face)
           ("{" font-lock-bracket-face)
           ("c_field" font-lock-property-name-face)
           (";" font-lock-delimiter-face)
           ("int" font-lock-type-face)
           ("c_call" font-lock-function-name-face)
           ("(" font-lock-bracket-face)
           ("c_item" font-lock-variable-name-face)
           (")" font-lock-bracket-face)
           ("c_number" font-lock-variable-name-face)
           ("=" font-lock-operator-face)
           ("8" font-lock-number-face)
           ("return" font-lock-keyword-face)
           ("c_call" font-lock-function-call-face)
           ("c_item" font-lock-variable-use-face)
           ("+" font-lock-operator-face)
           ("." font-lock-operator-face)
           ("c_field" font-lock-property-use-face)))
         (c++-ts-mode
          "#define CPP_MACRO 7\n// cpp-comment\nstruct CppItem { int cpp_field; };\nint cpp_call(CppItem cpp_item) { int cpp_number = 8; return cpp_call(cpp_item) + cpp_item.cpp_field; }\n"
          (("#define" font-lock-preprocessor-face)
           ("cpp-comment" font-lock-comment-face)
           ("struct" font-lock-keyword-face)
           ("CppItem" font-lock-type-face)
           ("{" font-lock-bracket-face)
           ("cpp_field" font-lock-property-name-face)
           (";" font-lock-delimiter-face)
           ("int" font-lock-type-face)
           ("cpp_call" font-lock-function-name-face)
           ("(" font-lock-bracket-face)
           ("cpp_item" font-lock-variable-name-face)
           (")" font-lock-bracket-face)
           ("cpp_number" font-lock-variable-name-face)
           ("=" font-lock-operator-face)
           ("8" font-lock-number-face)
           ("return" font-lock-keyword-face)
           ("cpp_call" font-lock-function-call-face)
           ("cpp_item" font-lock-variable-use-face)
           ("+" font-lock-operator-face)
           ("." font-lock-operator-face)
           ("cpp_field" font-lock-property-use-face)))
         (rust-ts-mode
          "/// rust-doc\nconst RUST_VALUE: i32 = 8;\nstruct RustItem { rust_field: i32 }\nfn rust_call(rust_item: RustItem) -> i32 { let rust_number = 9; rust_call(rust_item) + rust_item.rust_field }\n"
          (("rust-doc" font-lock-doc-face)
           ("const" font-lock-keyword-face)
           ("RUST_VALUE" font-lock-type-face)
           (":" font-lock-delimiter-face)
           ("i32" font-lock-type-face)
           ("=" font-lock-operator-face)
           ("8" font-lock-number-face)
           ("struct" font-lock-keyword-face)
           ("RustItem" font-lock-type-face)
           ("{" font-lock-bracket-face)
           ("rust_field" font-lock-property-name-face)
           ("fn" font-lock-keyword-face)
           ("rust_call" font-lock-function-name-face)
           ("(" font-lock-bracket-face)
           ("rust_item" font-lock-variable-name-face)
           ("->" font-lock-operator-face)
           ("let" font-lock-keyword-face)
           ("rust_number" font-lock-variable-name-face)
           ("=" font-lock-operator-face)
           ("9" font-lock-number-face)
           ("rust_call" font-lock-function-call-face)
           ("rust_item" font-lock-variable-use-face)
           ("." font-lock-delimiter-face)
           ("rust_field" font-lock-property-use-face)))
         (lua-ts-mode
          "-- lua-comment\nlocal lua_value = 8\nlocal lua_item = { lua_field = lua_value }\nfunction lua_call() local lua_number = 9 return lua_call() + lua_item.lua_field end\n"
          (("--" font-lock-comment-delimiter-face)
           ("lua-comment" font-lock-comment-face)
           ("local" font-lock-keyword-face)
           ("lua_value" font-lock-variable-name-face)
           ("=" font-lock-operator-face)
           ("8" font-lock-number-face)
           ("local" font-lock-keyword-face)
           ("lua_item" font-lock-variable-name-face)
           ("{" font-lock-bracket-face)
           ("lua_field" font-lock-property-name-face)
           ("function" font-lock-keyword-face)
           ("lua_call" font-lock-function-name-face)
           ("()" font-lock-bracket-face)
           ("lua_number" font-lock-variable-name-face)
           ("9" font-lock-number-face)
           ("return" font-lock-keyword-face)
           ("lua_call" font-lock-function-call-face)
           ("+" font-lock-operator-face)
           ("." font-lock-punctuation-face)
           ("lua_field" font-lock-property-use-face)))
         (python-ts-mode
          "# python-comment\nPY_VALUE = 8\nclass PythonItem:\n    def python_call(self):\n        python_number = 9\n        return python_call() + self.python_field\n"
          (("python-comment" font-lock-comment-face)
           ("PY_VALUE" font-lock-constant-face)
           ("=" font-lock-operator-face)
           ("8" font-lock-number-face)
           ("class" font-lock-keyword-face)
           ("PythonItem" font-lock-type-face)
           (":" font-lock-delimiter-face)
           ("def" font-lock-keyword-face)
           ("python_call" font-lock-function-name-face)
           ("(" font-lock-bracket-face)
           ("self" font-lock-keyword-face)
           (")" font-lock-bracket-face)
           ("python_number" font-lock-variable-name-face)
           ("=" font-lock-operator-face)
           ("9" font-lock-number-face)
           ("return" font-lock-keyword-face)
           ("python_call" font-lock-function-call-face)
           ("+" font-lock-operator-face)
           ("self" font-lock-keyword-face)
           ("." font-lock-delimiter-face)
           ("python_field" font-lock-property-use-face)))
         (js-ts-mode
          "// js-comment\nconst js_value = 8;\nclass JsItem { js_call(js_item) { const js_number = 9; return js_call(js_item) + js_item.js_field; } }\n"
          (("js-comment" font-lock-comment-face)
           ("const" font-lock-keyword-face)
           ("js_value" font-lock-variable-name-face)
           ("=" font-lock-operator-face)
           ("8" font-lock-number-face)
           (";" font-lock-delimiter-face)
           ("class" font-lock-keyword-face)
           ("JsItem" font-lock-type-face)
           ("{" font-lock-bracket-face)
           ("js_call" font-lock-function-name-face)
           ("(" font-lock-bracket-face)
           ("js_item" font-lock-variable-name-face)
           (")" font-lock-bracket-face)
           ("const" font-lock-keyword-face)
           ("js_number" font-lock-variable-name-face)
           ("=" font-lock-operator-face)
           ("9" font-lock-number-face)
           ("return" font-lock-keyword-face)
           ("js_call" font-lock-function-call-face)
           ("+" font-lock-operator-face)
           ("." font-lock-delimiter-face)
           ("js_field" font-lock-property-use-face)))
         (typescript-ts-mode
          "const ts_value: number = 8;\nclass TsItem { ts_call(ts_item: TsItem) { const ts_number = 9; return ts_call(ts_item) + ts_item.ts_member; } }\nconst ts_object = { ts_property: ts_value };\n"
          (("const" font-lock-keyword-face)
           ("ts_value" font-lock-variable-name-face)
           (":" font-lock-delimiter-face)
           ("number" font-lock-type-face)
           ("=" font-lock-operator-face)
           ("8" font-lock-number-face)
           (";" font-lock-delimiter-face)
           ("class" font-lock-keyword-face)
           ("TsItem" font-lock-type-face)
           ("{" font-lock-bracket-face)
           ("ts_call" font-lock-function-name-face)
           ("(" font-lock-bracket-face)
           ("ts_item" font-lock-variable-name-face)
           (":" font-lock-delimiter-face)
           ("TsItem" font-lock-type-face)
           (")" font-lock-bracket-face)
           ("ts_number" font-lock-variable-name-face)
           ("=" font-lock-operator-face)
           ("9" font-lock-number-face)
           ("return" font-lock-keyword-face)
           ("ts_call" font-lock-function-call-face)
           ("ts_item" font-lock-variable-use-face)
           ("+" font-lock-operator-face)
           ("ts_item" font-lock-variable-use-face)
           ("." font-lock-delimiter-face)
           ("ts_property" font-lock-property-use-face)))
         (tsx-ts-mode
          "const tsx_value: number = 8;\nconst tsx_item = <TsxItem tsx_field={tsx_value} />;\nconst tsx_result = tsx_call(tsx_value);\n"
          (("const" font-lock-keyword-face)
           ("tsx_value" font-lock-variable-name-face)
           (":" font-lock-delimiter-face)
           ("number" font-lock-type-face)
           ("8" font-lock-number-face)
           ("const" font-lock-keyword-face)
           ("tsx_item" font-lock-variable-name-face)
           ("TsxItem" typescript-ts-jsx-tag-face)
           ("tsx_field" typescript-ts-jsx-attribute-face)
           ("{" font-lock-bracket-face)
           ("tsx_value" font-lock-variable-use-face)
           ("}" font-lock-bracket-face)
           ("const" font-lock-keyword-face)
           ("tsx_result" font-lock-variable-name-face)
           ("tsx_call" font-lock-function-call-face)
           ("(" font-lock-bracket-face)
           ("tsx_value" font-lock-variable-use-face)
           (")" font-lock-bracket-face)
           (";" font-lock-delimiter-face)))))
    (let ((mode (nth 0 spec))
          (source (nth 1 spec))
          (tokens (nth 2 spec)))
      (with-temp-buffer
        (insert source)
        (funcall mode)
        (should (eq major-mode mode))
        (font-lock-ensure)
        (my/appearance-assert-rendered-faces my/appearance-font-lock-attributes)
        (my/appearance-assert-tokens tokens my/appearance-font-lock-attributes)))))

(ert-deftest my/appearance-eglot-inlay-hints-inherit-normal-height ()
  (require 'eglot)
  (load-theme 'mig-zenbones-light t)
  (should (eq (face-attribute 'eglot-inlay-hint-face :inherit nil) 'shadow))
  (should (= (face-attribute 'eglot-inlay-hint-face :height nil t) 1.0))
  (dolist (face '(eglot-type-hint-face eglot-parameter-hint-face))
    (should (eq (face-attribute face :inherit nil) 'eglot-inlay-hint-face))
    (should (= (face-attribute face :height nil t) 1.0))))

(ert-deftest my/appearance-markdown-inline-code-follows-default-metrics ()
  (require 'markdown-ts-mode)
  (require 'markdown-mode)
  (my/appearance-load-theme)
  (should (eq (face-attribute 'fixed-pitch :inherit nil) 'default))
  (should (equal (face-attribute 'fixed-pitch :family nil t)
                 (face-attribute 'default :family nil t)))
  (should (equal (face-attribute 'fixed-pitch :height nil t)
                 (face-attribute 'default :height nil t)))
  (should (equal (face-attribute 'markdown-ts-code-span :inherit nil)
                 '(markdown-ts-code-block font-lock-constant-face)))
  (should (= (face-attribute 'markdown-ts-code-span :height nil t) 1.0))
  (should (equal (face-attribute 'markdown-ts-code-span :family nil t)
                 (face-attribute 'fixed-pitch :family nil t)))
  (should (equal (face-attribute 'markdown-inline-code-face :inherit nil)
                 '(markdown-code-face markdown-pre-face)))
  (should (= (face-attribute 'markdown-inline-code-face :height nil t) 1.0))
  (should (equal (face-attribute 'markdown-inline-code-face :family nil t)
                 (face-attribute 'fixed-pitch :family nil t)))
  (dolist (mode '(markdown-ts-mode markdown-mode gfm-mode))
    (with-temp-buffer
      (insert "outside `inline`\n")
      (funcall mode)
      (font-lock-ensure)
      (goto-char (point-min))
      (search-forward "inline")
      (let ((inline-face (if (eq mode 'markdown-ts-mode)
                             'markdown-ts-code-span
                           'markdown-inline-code-face)))
        (should (eq major-mode mode))
        (should (equal (get-text-property (1- (point)) 'face)
                       (list inline-face)))
        (text-scale-increase 1)
        (should (= text-scale-mode-amount 1))
        (should (equal (assq 'default face-remapping-alist)
                       `(default (:height ,(expt text-scale-mode-step 1))
                                  default)))
        (should-not (assq inline-face face-remapping-alist))))))

(ert-deftest my/appearance-native-completion-keeps-fixed-height-settings ()
  (should (= completions-max-height 14))
  (should completion-eager-display)
  (should completion-eager-update)
  (should (eq completions-format 'one-column))
  (save-window-excursion
    (dolist (line-count '(2 30))
      (with-current-buffer-window
          "*Completions*"
          '((display-buffer-at-bottom)
            (window-height . completions--fit-window-to-buffer))
          nil
        (completion-list-mode)
        (dotimes (_ line-count)
          (insert "candidate\n")))
      (let ((window (get-buffer-window "*Completions*")))
        (should (window-live-p window))
        (with-current-buffer (window-buffer window)
          (should (local-variable-p 'window-min-height))
          (should (= window-min-height completions-max-height)))
        (should (= (window-total-height window) 14))
        (delete-window window))
      (kill-buffer "*Completions*"))))

(ert-deftest my/appearance-palette-contract ()
  (my/appearance-load-theme)
  (require 'ansi-color)
  (require 'compile)
  (require 'diff-hl)
  (require 'diff-mode)
  (require 'eglot)
  (require 'flymake)
  (require 'typescript-ts-mode)
  (dolist
      (spec
       '((default :foreground "#2C363C" :background "#F0EDEC")
         (cursor :foreground "#F0EDEC" :background "#2C363C")
         (region :foreground "#2C363C" :background "#CBD9E3" :extend t)
         (highlight :background "#E9E4E2" :extend t)
         (line-number :foreground "#A4968F" :weight normal :underline nil)
         (match :foreground "#2C363C" :background "#DEB9D6")
         (isearch :foreground "#F0EDEC" :background "#C074B2" :weight bold)
         (mode-line :foreground "#2C363C" :background "#D6CDC9")
         (error :foreground "#A8334C")
         (warning :foreground "#944927")
         (success :foreground "#4F6C31")
         (compilation-error :foreground "#A8334C" :weight bold)
         (compilation-warning :foreground "#944927")
         (compilation-info :foreground "#4F6C31")
         (flymake-error :underline (:style wave :color "#A8334C"))
         (flymake-warning :underline (:style wave :color "#944927"))
         (flymake-note :underline (:style wave :color "#4F6C31"))
         (eglot-inlay-hint-face :foreground "#A38C80" :background "#EBE7E6"
                                :height 1.0)
         (diff-added :foreground "#4F6C31" :background "#CBE5B8" :extend t)
         (diff-removed :foreground "#A8334C" :background "#EBD8DA" :extend t)
         (diff-changed :foreground "#286486" :background "#D4DEE7" :extend t)
         (diff-refine-added :foreground "#2C363C" :background "#CBE5B8" :weight bold)
         (diff-refine-removed :foreground "#2C363C" :background "#EBD8DA" :weight bold)
         (diff-refine-changed :foreground "#2C363C" :background "#A9BED1" :weight bold)
         (diff-context :foreground "#2C363C")
         (diff-header :foreground "#948985")
         (diff-file-header :foreground "#2C363C" :weight bold)
         (diff-hunk-header :foreground "#A4968F" :background "#E9E4E2")
         (diff-index :foreground "#944927")
         (diff-changed-unspecified :foreground "#286486" :background "#D4DEE7"
                                   :extend t)
         (diff-indicator-added :foreground "#4F6C31" :weight bold)
         (diff-indicator-removed :foreground "#A8334C" :weight bold)
         (diff-indicator-changed :foreground "#286486" :weight bold)
         (diff-function :foreground "#4F5E68" :weight bold)
         (diff-nonexistent :foreground "#A8334C" :background "#EBD8DA" :extend t)))
    (my/appearance-assert-face-attributes (car spec) (cdr spec)))
  (dolist (spec my/appearance-font-lock-attributes)
    (my/appearance-assert-face-attributes (car spec) (cdr spec)))
  (dolist
      (spec
       '((diff-hl-insert diff-added "#4F6C31" "#CBE5B8")
         (diff-hl-change diff-changed "#286486" "#D4DEE7")
         (diff-hl-delete diff-removed "#A8334C" "#EBD8DA")
         (diff-hl-reference-insert diff-hl-insert "#4F6C31" "#CBE5B8")
         (diff-hl-reference-change diff-hl-change "#286486" "#D4DEE7")
         (diff-hl-reference-delete diff-hl-delete "#A8334C" "#EBD8DA")))
    (should (eq (face-attribute (nth 0 spec) :inherit nil) (nth 1 spec)))
    (my/appearance-assert-face-attributes
     (nth 0 spec) (list :foreground (nth 2 spec) :background (nth 3 spec))))
  (dolist
      (spec
       '((ansi-color-black "#F0EDEC")
         (ansi-color-red "#A8334C")
         (ansi-color-green "#4F6C31")
         (ansi-color-yellow "#944927")
         (ansi-color-blue "#286486")
         (ansi-color-magenta "#88507D")
         (ansi-color-cyan "#3B8992")
         (ansi-color-white "#2C363C")
         (ansi-color-bright-black "#CFC1BA")
         (ansi-color-bright-red "#94253E")
         (ansi-color-bright-green "#3F5A22")
         (ansi-color-bright-yellow "#803D1C")
         (ansi-color-bright-blue "#1D5573")
         (ansi-color-bright-magenta "#7B3B70")
         (ansi-color-bright-cyan "#2B747C")
         (ansi-color-bright-white "#4F5E68")))
    (my/appearance-assert-face-attributes
     (nth 0 spec) (list :foreground (nth 1 spec) :background (nth 1 spec)))))

(ert-deftest my/appearance-tree-sitter-tokens-use-level-four-faces ()
  (my/appearance-load-theme)
  (my/appearance-verify-tree-sitter-tokens))

(ert-deftest my/appearance-markdown-tree-sitter-and-classic-modes-match ()
  (my/appearance-load-theme)
  (require 'markdown-mode)
  (require 'markdown-ts-mode)
  (should (treesit-ready-p 'markdown t))
  (should (treesit-ready-p 'markdown-inline t))
  (let ((source
         "# Heading *emphasis*\n\n> quote\n\n- [x] item\n\n[link](https://example.com)\n\n| head | cell |\n| --- | --- |\n| one | two |\n\n```elisp\n(code)\n```\n\n`inline`\n"))
    (with-temp-buffer
      (insert source)
      (markdown-ts-mode)
      (font-lock-ensure)
      (my/appearance-assert-rendered-faces my/appearance-markdown-ts-attributes)
      (my/appearance-assert-tokens
       '(("#" markdown-ts-delimiter)
         ("Heading" markdown-ts-heading-1)
         ("emphasis" markdown-ts-emphasis)
         (">" markdown-ts-delimiter)
         ("quote" markdown-ts-block-quote)
         ("-" markdown-ts-list-marker)
         ("[x]" markdown-ts-task-checked)
         ("link" markdown-ts-link)
         ("https://example.com" markdown-ts-link-destination)
         ("head" markdown-ts-table-header)
         ("---" markdown-ts-table-delimiter-cell)
         ("one" markdown-ts-table-cell)
         ("```" markdown-ts-delimiter)
         ("elisp" markdown-ts-language-keyword)
         ("inline" markdown-ts-code-span))
       my/appearance-markdown-ts-attributes)
      (goto-char (point-min))
      (search-forward "(code)")
      (let ((code-block
             (seq-find (lambda (overlay)
                         (overlay-get overlay 'markdown-ts-code-block))
                       (overlays-at (match-beginning 0)))))
        (should code-block)
        (should (eq (overlay-get code-block 'face) 'markdown-ts-code-block))
        (my/appearance-assert-face-attributes
         'markdown-ts-code-block
         (cdr (assq 'markdown-ts-code-block my/appearance-markdown-ts-attributes)))))
    (dolist (mode '(markdown-mode gfm-mode))
      (with-temp-buffer
        (insert source)
        (funcall mode)
        (font-lock-ensure)
        (my/appearance-assert-tokens
         '(("#" markdown-header-delimiter-face)
           ("Heading" markdown-header-face-1)
           ("emphasis" markdown-italic-face)
           (">" markdown-markup-face)
           ("quote" markdown-blockquote-face)
           ("-" markdown-list-face)
           ("link" markdown-link-face)
           ("https://example.com" markdown-url-face)
           ("head" markdown-table-face)
           ("elisp" markdown-language-keyword-face)
           ("(code)" markdown-pre-face)
           ("inline" markdown-inline-code-face))
         '((markdown-header-delimiter-face :foreground "#8E817B")
           (markdown-header-face-1 :foreground "#2C363C" :weight bold)
           (markdown-italic-face :slant italic)
           (markdown-markup-face :foreground "#8E817B")
           (markdown-blockquote-face :foreground "#556570" :slant italic)
           (markdown-list-face :foreground "#4F5E68" :weight bold)
           (markdown-link-face :foreground "#44525B" :underline t)
           (markdown-url-face :foreground "#948985" :underline t)
           (markdown-table-face :foreground "#2C363C")
           (markdown-language-keyword-face :foreground "#2C363C" :weight bold)
           (markdown-pre-face :foreground "#6A5549" :background "#EBE7E6" :extend t)
           (markdown-inline-code-face :foreground "#6A5549" :background "#EBE7E6"
                                      :height 1.0 :extend nil))))))
  (dolist
      (pair
       '((markdown-header-face-1 markdown-ts-heading-1)
         (markdown-header-delimiter-face markdown-ts-delimiter)
         (markdown-blockquote-face markdown-ts-block-quote)
         (markdown-list-face markdown-ts-task-checked)
         (markdown-link-face markdown-ts-link)
         (markdown-url-face markdown-ts-link-destination)
         (markdown-table-face markdown-ts-table)
         (markdown-pre-face markdown-ts-code-block)
         (markdown-inline-code-face markdown-ts-code-span)))
    (dolist (attribute '(:foreground :background :height))
      (should (equal (face-attribute (nth 0 pair) attribute nil t)
                     (face-attribute (nth 1 pair) attribute nil t))))))

(ert-deftest my/appearance-org-todo-keywords-use-the-theme-palette ()
  (my/appearance-load-theme)
  (require 'org)
  (let ((expected
         '(("PROJ" :foreground "#286486" :weight bold)
           ("TODO" :foreground "#2C363C" :weight bold :underline t)
           ("REVIEW" :foreground "#88507D" :weight bold)
           ("POST" :foreground "#3B8992" :weight bold)
           ("DOING" :foreground "#944927" :weight bold)
           ("BLOCKED" :foreground "#A8334C" :weight bold)
           ("DONE" :foreground "#4F6C31" :weight bold)
           ("CANCELED" :foreground "#948985" :strike-through t))))
    (should (equal org-todo-keyword-faces expected))
    (with-temp-buffer
      (dolist (entry expected)
        (insert "* " (car entry) " task\n"))
      (org-mode)
      (font-lock-ensure)
      (goto-char (point-min))
      (dolist (entry expected)
        (should (search-forward (car entry) nil t))
        (let ((rendered (get-text-property (match-beginning 0) 'face)))
          (should (equal (car rendered) (cdr entry)))
          (should (memq 'org-level-1 (cdr rendered))))))))

(ert-deftest my/appearance-package-families-inherit-the-shared-palette ()
  (my/appearance-load-theme)
  (dolist
      (feature
       '(eglot markdown-mode markdown-ts-mode org org-agenda org-roam-mode
               org-roam-overlay org-roam-dailies org-ref org-ref-citation-links
               org-ref-glossary org-ref-label-link org-ref-ref-links magit
               magit-reflog magit-sequence magit-blame magit-bisect git-commit
               git-rebase dape consult consult-imenu embark which-key evil dired
               gptel gptel-context gptel-rewrite))
    (require feature))
  (dolist
      (spec
       '((markdown-inline-code-face (markdown-code-face markdown-pre-face)
                                    :foreground "#6A5549" :background "#EBE7E6"
                                    :height 1.0 :extend nil)
         (markdown-ts-code-span (markdown-ts-code-block font-lock-constant-face)
                                :foreground "#6A5549" :background "#EBE7E6"
                                :height 1.0 :extend nil)
         (org-headline-todo org-todo :foreground "#2C363C" :weight bold :underline t)
         (org-agenda-calendar-daterange org-date :foreground "#944927")
         (org-roam-header-line header-line :foreground "#2C363C" :background "#D6CDC9")
         (org-ref-bad-cite-key-face error :foreground "#A8334C")
         (magit-process-ok success :foreground "#4F6C31")
         (git-commit-overlong-summary error :foreground "#A8334C")
         (git-rebase-hash magit-hash :foreground "#948985")
         (dape-inlay-hint-face eglot-inlay-hint-face :foreground "#A38C80"
                               :background "#EBE7E6" :height 1.0)
         (consult-async-running warning :foreground "#944927")
         (embark-target highlight :background "#E9E4E2" :extend t)
         (which-key-key-face unspecified :foreground "#2C363C" :weight bold)
         (evil-ex-search isearch :foreground "#F0EDEC" :background "#C074B2")
         (dired-broken-symlink error :foreground "#A8334C")
         (gptel-context-highlight-face unspecified :foreground "#2C363C"
                                       :background "#EBE7E6")))
    (let ((face (nth 0 spec))
          (parent (nth 1 spec))
          (attributes (nthcdr 2 spec)))
      (should (equal (face-attribute face :inherit nil) parent))
      (my/appearance-assert-face-attributes face attributes)))
  (my/appearance-verify-tree-sitter-tokens)
  (dolist
      (spec
       '((nim-font-lock-export-face font-lock-builtin-face)
         (nim-font-lock-pragma-face font-lock-preprocessor-face)
         (nim-non-overloadable-face font-lock-builtin-face)
         (nim-font-lock-number-face font-lock-number-face)
         (zig-multiline-string-face font-lock-string-face)
         (php-string font-lock-string-face)
         (php-keyword font-lock-keyword-face)
         (php-builtin font-lock-builtin-face)
         (php-function-name font-lock-function-name-face)
         (php-function-call-standard font-lock-function-call-face)
         (php-variable-name font-lock-variable-name-face)
         (php-property-name font-lock-property-name-face)
         (php-type font-lock-type-face)
         (php-constant font-lock-constant-face)
         (php-php-tag font-lock-preprocessor-face)
         (php-doc-annotation-tag font-lock-doc-markup-face)
         (php-operator font-lock-operator-face)))
    (require (pcase (car spec)
               ((or 'nim-font-lock-export-face 'nim-font-lock-pragma-face
                    'nim-non-overloadable-face 'nim-font-lock-number-face) 'nim-mode)
               ('zig-multiline-string-face 'zig-mode)
               (_ 'php-mode)))
    (should (eq (face-attribute (nth 0 spec) :inherit nil) (nth 1 spec)))
    (should (equal (face-attribute (nth 0 spec) :foreground nil t)
                   (face-attribute (nth 1 spec) :foreground nil t))))
  (require 'odin-mode)
  (with-temp-buffer
    (insert "package fallback\nmain :: proc() {}\n")
    (odin-mode)
    (font-lock-ensure)
    (my/appearance-assert-rendered-faces my/appearance-font-lock-attributes)
    (my/appearance-assert-tokens
     '(("package" font-lock-keyword-face)
       ("main" font-lock-function-name-face)
       ("proc" font-lock-keyword-face))
     my/appearance-font-lock-attributes)))

(ert-deftest my/appearance-ghostel-uses-the-ansi-palette ()
  (require 'ghostel)
  (my/appearance-load-theme)
  (my/appearance-assert-face-attributes
   'ghostel-default '(:foreground "#2C363C" :background "#F0EDEC"))
  (should (equal (face-attribute 'ghostel-fake-cursor :box nil t)
                 '(:line-width (-1 . -1) :color "#2C363C")))
  (should (eq (face-attribute 'ghostel-fake-cursor-box :inherit nil) 'cursor))
  (my/appearance-assert-face-attributes
   'ghostel-fake-cursor-box '(:foreground "#F0EDEC" :background "#2C363C"))
  (let ((palette
         '((ghostel-color-black ansi-color-black "#F0EDEC")
           (ghostel-color-red ansi-color-red "#A8334C")
           (ghostel-color-green ansi-color-green "#4F6C31")
           (ghostel-color-yellow ansi-color-yellow "#944927")
           (ghostel-color-blue ansi-color-blue "#286486")
           (ghostel-color-magenta ansi-color-magenta "#88507D")
           (ghostel-color-cyan ansi-color-cyan "#3B8992")
           (ghostel-color-white ansi-color-white "#2C363C")
           (ghostel-color-bright-black ansi-color-bright-black "#CFC1BA")
           (ghostel-color-bright-red ansi-color-bright-red "#94253E")
           (ghostel-color-bright-green ansi-color-bright-green "#3F5A22")
           (ghostel-color-bright-yellow ansi-color-bright-yellow "#803D1C")
           (ghostel-color-bright-blue ansi-color-bright-blue "#1D5573")
           (ghostel-color-bright-magenta ansi-color-bright-magenta "#7B3B70")
           (ghostel-color-bright-cyan ansi-color-bright-cyan "#2B747C")
           (ghostel-color-bright-white ansi-color-bright-white "#4F5E68"))))
    (should (equal ghostel-color-palette
                   (vconcat (mapcar #'car palette))))
    (dolist (spec palette)
      (should (eq (face-attribute (nth 0 spec) :inherit nil) (nth 1 spec)))
      (my/appearance-assert-face-attributes
       (nth 0 spec) (list :foreground (nth 2 spec) :background (nth 2 spec)))))
  (should (null ghostel-bold-color)))

;;; appearance-test.el ends here
