;;; appearance-test.el --- Appearance behavior tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'face-remap)

(load (expand-file-name "init.el" (file-name-directory (or load-file-name buffer-file-name)))
      nil nil nil t)

(ert-deftest my/appearance-eglot-inlay-hints-inherit-normal-height ()
  (require 'eglot)
  (load-theme 'mig-zenbones-light t)
  (should (eq (face-attribute 'eglot-inlay-hint-face :inherit nil) 'shadow))
  (should (= (face-attribute 'eglot-inlay-hint-face :height nil t) 1.0))
  (dolist (face '(eglot-type-hint-face eglot-parameter-hint-face))
    (should (eq (face-attribute face :inherit nil) 'eglot-inlay-hint-face))
    (should (= (face-attribute face :height nil t) 1.0))))

(ert-deftest my/appearance-markdown-inline-code-follows-default-metrics ()
  (require 'markdown-ts-mode)
  (require 'markdown-mode)
  (should (eq (face-attribute 'fixed-pitch :inherit nil) 'default))
  (should (equal (face-attribute 'fixed-pitch :family nil t)
                 (face-attribute 'default :family nil t)))
  (should (equal (face-attribute 'fixed-pitch :height nil t)
                 (face-attribute 'default :height nil t)))
  (should (equal (face-attribute 'markdown-ts-code-span :inherit nil)
                 '(markdown-ts-code-block font-lock-constant-face)))
  (should (= (face-attribute 'markdown-ts-code-span :height nil t) 1.0))
  (should (equal (face-attribute 'markdown-ts-code-span :family nil t)
                 (face-attribute 'fixed-pitch :family nil t)))
  (should (equal (face-attribute 'markdown-inline-code-face :inherit nil)
                 '(markdown-code-face markdown-pre-face)))
  (should (= (face-attribute 'markdown-inline-code-face :height nil t) 1.0))
  (should (equal (face-attribute 'markdown-inline-code-face :family nil t)
                 (face-attribute 'fixed-pitch :family nil t)))
  (dolist (mode '(markdown-ts-mode markdown-mode gfm-mode))
    (with-temp-buffer
      (insert "outside `inline`\n")
      (funcall mode)
      (font-lock-ensure)
      (goto-char (point-min))
      (search-forward "inline")
      (let ((inline-face (if (eq mode 'markdown-ts-mode)
                             'markdown-ts-code-span
                           'markdown-inline-code-face)))
        (should (eq major-mode mode))
        (should (equal (get-text-property (1- (point)) 'face)
                       (list inline-face)))
        (text-scale-increase 1)
        (should (= text-scale-mode-amount 1))
        (should (equal (assq 'default face-remapping-alist)
                       `(default (:height ,(expt text-scale-mode-step 1))
                                  default)))
        (should-not (assq inline-face face-remapping-alist))))))

(ert-deftest my/appearance-native-completion-keeps-fixed-height-settings ()
  (should (= completions-max-height 14))
  (should completion-eager-display)
  (should completion-eager-update)
  (should (eq completions-format 'one-column))
  (save-window-excursion
    (dolist (line-count '(2 30))
      (with-current-buffer-window
          "*Completions*"
          '((display-buffer-at-bottom)
            (window-height . completions--fit-window-to-buffer))
          nil
        (completion-list-mode)
        (dotimes (_ line-count)
          (insert "candidate\n")))
      (let ((window (get-buffer-window "*Completions*")))
        (should (window-live-p window))
        (with-current-buffer (window-buffer window)
          (should (local-variable-p 'window-min-height))
          (should (= window-min-height completions-max-height)))
        (should (= (window-total-height window) 14))
        (delete-window window))
      (kill-buffer "*Completions*"))))

;;; appearance-test.el ends here
