;;; gui-smoke-test.el --- Graphical Emacs acceptance smoke tests -*- lexical-binding: t; -*-

;;; Commentary:

;; Load this file in an isolated Emacs that has already loaded init.el.  The
;; tests dispatch configured keys directly and replace prompt, terminal, and
;; agent-process boundaries with in-memory implementations.

;;; Code:

(require 'cl-lib)
(require 'ert)
(require 'face-remap)
(require 'markdown-ts-mode)

(defun my/gui-smoke-kill-buffer (buffer)
  "Discard BUFFER without allowing a smoke fixture to prompt for saving."
  (when (buffer-live-p buffer)
    (with-current-buffer buffer
      (set-buffer-modified-p nil))
    (kill-buffer buffer)))

(ert-deftest my/gui-smoke-search-bindings-and-prompts ()
  (require 'consult)
  (require 'counsel)
  (let ((directory (file-name-as-directory
                    (make-temp-file "my-gui-smoke-search-" t)))
        (buffer (generate-new-buffer " *gui-smoke-search*"))
        fzf-prompt fzf-directory fzf-initial fzf-command
        grep-prompt grep-initial)
    (unwind-protect
        (save-window-excursion
          (with-current-buffer buffer
            (setq default-directory directory)
            (evil-normal-state)
            (should (eq (key-binding (kbd "C-p")) #'my/find-file-fzf-root))
            (should (eq (key-binding (kbd "SPC s g")) #'consult-ripgrep))
            (let ((real-executable-find (symbol-function 'executable-find))
                  (counsel--fzf-dir nil))
              (cl-letf (((symbol-function 'executable-find)
                         (lambda (program &optional remote)
                           (if (member program '("fd" "fzf"))
                               (concat "/gui-smoke/" program)
                             (funcall real-executable-find program remote))))
                        ((symbol-function 'ivy-read)
                         (lambda (prompt _collection &rest arguments)
                           (setq fzf-prompt prompt
                                 fzf-directory counsel--fzf-dir
                                 fzf-initial (plist-get arguments :initial-input)
                                 fzf-command counsel-fzf-cmd)
                           nil)))
                (call-interactively (key-binding (kbd "C-p")))))
            (should (string-match-p "fzf" fzf-prompt))
            (should (equal fzf-directory directory))
            (should-not fzf-initial)
            (should (equal fzf-command my/file-picker-local-fzf-command))
            (cl-letf (((symbol-function 'consult--read)
                       (lambda (_collection &rest arguments)
                         (setq grep-prompt (plist-get arguments :prompt)
                               grep-initial (plist-get arguments :initial))
                         nil)))
              (call-interactively (key-binding (kbd "SPC s g"))))
            (should (string-match-p "Ripgrep" grep-prompt))
            (should-not grep-initial)
            (should-not consult-async-split-style)))
      (my/gui-smoke-kill-buffer buffer)
      (delete-directory directory))))

(ert-deftest my/gui-smoke-file-visit-and-evil-jump-return ()
  (let* ((source-file (make-temp-file "my-gui-smoke-source-" nil ".el"))
         (target-file (make-temp-file "my-gui-smoke-target-" nil ".el"))
         (source (find-file-noselect source-file))
         (target nil)
         (evil--jumps-window-jumps (make-hash-table :test #'eq))
         (evil--jumps-jumping nil)
         source-point)
    (unwind-protect
        (save-window-excursion
          (switch-to-buffer source)
          (with-current-buffer source
            (erase-buffer)
            (insert "source line\n")
            (goto-char 4)
            (setq source-point (point))
            (set-buffer-modified-p nil))
          (evil-normal-state)
          (should (eq (key-binding (kbd "C-x C-f")) #'my/find-file))
          (cl-letf (((symbol-function 'my/file-picker-hierarchical-session)
                     (lambda (&rest _arguments) target-file)))
            (call-interactively (key-binding (kbd "C-x C-f"))))
          (setq target (current-buffer))
          (should (equal (buffer-file-name target) target-file))
          (evil-normal-state)
          (should (eq (key-binding (kbd "C-o")) #'evil-jump-backward))
          (call-interactively (key-binding (kbd "C-o")))
          (should (eq (current-buffer) source))
          (should (= (point) source-point)))
      (my/gui-smoke-kill-buffer source)
      (my/gui-smoke-kill-buffer target)
      (delete-file source-file)
      (delete-file target-file))))

(ert-deftest my/gui-smoke-markdown-tree-sitter-list-editing-and-jumps ()
  (let ((buffer (generate-new-buffer " *gui-smoke-markdown*")))
    (unwind-protect
        (save-window-excursion
          (switch-to-buffer buffer)
          (insert "- parent\n- child\n")
          (markdown-ts-mode)
          (font-lock-ensure)
          (goto-char (point-min))
          (search-forward "child")
          (evil-insert-state)
          (should (eq (key-binding (kbd "TAB")) #'my/markdown-insert-tab))
          (should (eq (key-binding (kbd "<tab>")) #'my/markdown-insert-tab))
          (should (eq (key-binding (kbd "S-TAB")) #'my/markdown-insert-backtab))
          (should (eq (key-binding (kbd "<backtab>"))
                      #'my/markdown-insert-backtab))
          (call-interactively (key-binding (kbd "TAB")))
          (should (equal (buffer-string) "- parent\n  - child\n"))
          (call-interactively (key-binding (kbd "S-TAB")))
          (should (equal (buffer-string) "- parent\n- child\n"))
          (erase-buffer)
          (insert "- parent\n  - child\n")
          (font-lock-ensure)
          (goto-char (point-min))
          (search-forward "child")
          (evil-insert-state)
          (should (eq (key-binding (kbd "RET")) #'my/markdown-ts-return))
          (call-interactively (key-binding (kbd "RET")))
          (call-interactively (key-binding (kbd "RET")))
          (should (equal (buffer-string) "- parent\n  - child\n- \n"))
          (evil-normal-state)
          (dolist (key '("TAB" "C-i"))
            (should (eq (key-binding (kbd key)) #'evil-jump-forward)))
          (evil-visual-state)
          (dolist (key '("TAB" "C-i"))
            (should (eq (key-binding (kbd key)) #'evil-jump-forward))))
      (my/gui-smoke-kill-buffer buffer))))

(ert-deftest my/gui-smoke-cwd-terminal-entry-and-send-target ()
  (let* ((directory (file-name-as-directory
                     (make-temp-file "my-gui-smoke-terminal-" t)))
         (source (generate-new-buffer " *gui-smoke-terminal-source*"))
         (terminal (generate-new-buffer " *gui-smoke-terminal*"))
         (process 'gui-smoke-terminal-process)
         (my/cwd-terminal-targets nil)
         target creations)
    (unwind-protect
        (save-window-excursion
          (with-current-buffer source
            (setq default-directory directory))
          (switch-to-buffer source)
          (evil-normal-state)
          (should (eq (key-binding (kbd "s-j")) #'my/open-cwd-terminal))
          (let ((real-require (symbol-function 'require)))
            (cl-letf (((symbol-function 'require)
                       (lambda (feature &optional filename noerror)
                         (if (eq feature 'ghostel)
                             feature
                           (funcall real-require feature filename noerror))))
                      ((symbol-function 'ghostel-buffer-list)
                       (lambda () (list terminal)))
                      ((symbol-function 'ghostel-create)
                       (lambda (name action)
                         (push (list name action default-directory) creations)
                         terminal))
                      ((symbol-function 'get-buffer-process)
                       (lambda (buffer)
                         (and (eq buffer terminal) process)))
                      ((symbol-function 'process-live-p)
                       (lambda (candidate) (eq candidate process)))
                      ((symbol-function 'pop-to-buffer)
                       (lambda (buffer &rest _arguments)
                         (switch-to-buffer buffer)))
                      ((symbol-function 'my/tab-set-current-property)
                       (lambda (property value)
                         (when (eq property 'my/send-text-last-target)
                           (setq target value))
                         value)))
              (call-interactively (key-binding (kbd "s-j")))
              (switch-to-buffer source)
              (evil-normal-state)
              (call-interactively (key-binding (kbd "s-j")))))
          (should (equal (nreverse creations)
                         (list (list nil my/right-split-action directory))))
          (should (equal target
                         (list :type 'ghostel :buffer terminal :process process)))
          (should (equal (alist-get directory my/cwd-terminal-targets nil nil #'equal)
                         target)))
      (my/gui-smoke-kill-buffer source)
      (my/gui-smoke-kill-buffer terminal)
      (delete-directory directory))))

(ert-deftest my/gui-smoke-agent-entry-selects-an-in-memory-companion ()
  (let ((source (generate-new-buffer " *gui-smoke-agent-source*"))
        (agent (generate-new-buffer " *gui-smoke-agent*"))
        created)
    (unwind-protect
        (save-window-excursion
          (switch-to-buffer source)
          (evil-normal-state)
          (should (eq (key-binding (kbd "s-a"))
                      #'my/work-codex-and-select-agent))
          (cl-letf (((symbol-function 'my/work-codex)
                     (lambda (&optional force)
                       (should-not force)
                       (setq created t)
                       (switch-to-buffer agent)))
                    ((symbol-function 'my/layout-cached-companion)
                     (lambda (layout)
                       (should (eq layout 'agent))
                       agent)))
            (call-interactively (key-binding (kbd "s-a"))))
          (should created)
          (should (eq (window-buffer (selected-window)) agent)))
      (my/gui-smoke-kill-buffer source)
      (my/gui-smoke-kill-buffer agent))))

(ert-deftest my/gui-smoke-writing-mode-heading-gutter-and-mode-line-scale ()
  (load-theme 'mig-zenbones-light t)
  (let ((writing (generate-new-buffer " *gui-smoke-writing*"))
        (other (generate-new-buffer " *gui-smoke-writing-other*")))
    (unwind-protect
        (save-window-excursion
          (switch-to-buffer writing)
          (insert "# Heading\n\nProse\n")
          (markdown-ts-mode)
          (font-lock-ensure)
          (display-line-numbers-mode 1)
          (evil-normal-state)
          (should (eq (key-binding (kbd "SPC Z")) #'my/write-mode))
          (call-interactively (key-binding (kbd "SPC Z")))
          (let ((scale (expt text-scale-mode-step text-scale-mode-amount)))
            (should (= text-scale-mode-amount 3))
            (should-not display-line-numbers-mode)
            (should my/write-mode-line-scale-cookie)
            (should (equal (assq 'mode-line face-remapping-alist)
                           `(mode-line (:height ,scale) mode-line))))
          (should (eq (face-attribute 'line-number :inherit nil) 'default))
          (should (eq (face-attribute 'line-number-current-line :inherit nil)
                      'line-number))
          (should (equal (face-attribute 'markdown-ts-heading-1 :foreground nil t)
                         "#2C363C"))
          (should (equal (face-attribute 'org-level-1 :foreground nil t)
                         "#2C363C"))
          (with-current-buffer other
            (should-not (local-variable-p 'my/write-mode-line-scale-cookie))
            (should-not (assq 'mode-line face-remapping-alist)))
          (with-current-buffer writing
            (my/default-mode)
            (should-not my/write-mode-line-scale-cookie)
            (should-not (assq 'mode-line face-remapping-alist))))
      (my/gui-smoke-kill-buffer writing)
      (my/gui-smoke-kill-buffer other))))

(provide 'gui-smoke-test)

;;; gui-smoke-test.el ends here
