;;; leader-bindings-test.el --- Leader binding behavior tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)

(load (expand-file-name "init.el" (file-name-directory (or load-file-name buffer-file-name)))
      nil nil nil t)

(require 'magit)
(require 'ghostel)
(require 'evil-ghostel)
(require 'olivetti)
(require 'which-key)

(ert-deftest my/leader-bindings-programming-line-numbers-and-toggles ()
  (should (eq display-line-numbers-type 'relative))
  (with-temp-buffer
    (emacs-lisp-mode)
    (should display-line-numbers-mode)
    (dolist (state '(evil-normal-state evil-visual-state))
      (funcall state)
      (let ((direct (key-binding (kbd "SPC l")))
            (nested (key-binding (kbd "SPC h l"))))
        (should (eq direct 'display-line-numbers-mode))
        (should (eq direct nested))
        (call-interactively direct)
        (should-not display-line-numbers-mode)
        (call-interactively nested)
        (should display-line-numbers-mode))))
  (dolist (mode '(text-mode org-mode shell-mode special-mode))
    (with-temp-buffer
      (funcall mode)
      (should-not display-line-numbers-mode))))

(ert-deftest my/leader-bindings-writing-commands-and-labels ()
  (with-temp-buffer
    (dolist (state '(evil-normal-state evil-visual-state))
      (funcall state)
      (should (eq (key-binding (kbd "SPC Z")) 'my/write-mode))
      (should (eq (key-binding (kbd "SPC z")) 'my/write-mode-no-zoom))
      (should (eq (key-binding (kbd "SPC v")) 'my/default-mode)))
    (evil-normal-state)
    (let ((bindings (which-key--get-keymap-bindings
                     (key-binding (kbd "SPC")))))
      (should (equal (assoc "Z" bindings) '("Z" . "zen mode")))
      (should (equal (assoc "z" bindings) '("z" . "zen mode no zoom")))
      (should (equal (assoc "v" bindings) '("v" . "code mode"))))
    (display-line-numbers-mode 1)
    (call-interactively (key-binding (kbd "SPC Z")))
    (should (= olivetti-body-width 60))
    (should (= text-scale-mode-amount 3))
    (should-not display-line-numbers-mode)
    (call-interactively (key-binding (kbd "SPC z")))
    (should (= olivetti-body-width 120))
    (should (= text-scale-mode-amount 0))
    (should-not display-line-numbers-mode)
    (call-interactively (key-binding (kbd "SPC v")))
    (should-not olivetti-mode)
    (should (= text-scale-mode-amount 0))
    (should display-line-numbers-mode)
    (dolist (state '(evil-insert-state evil-emacs-state))
      (funcall state)
      (should (eq (key-binding (kbd "SPC")) 'self-insert-command))
      (should-not (key-binding (kbd "SPC Z")))
      (should-not (key-binding (kbd "SPC z")))
      (should-not (key-binding (kbd "SPC v"))))))

(ert-deftest my/leader-bindings-magit-state-precedence ()
  (dolist (mode-and-native-space
           '((magit-status-mode . magit-diff-show-or-scroll-up)
             (magit-diff-mode . scroll-up)
             (magit-log-mode . magit-diff-show-or-scroll-up)
             (magit-process-mode . magit-diff-show-or-scroll-up)))
    (with-temp-buffer
      (funcall (car mode-and-native-space))
      (dolist (state-and-leader
               `((evil-normal-state . ,my/normal-leader-map)
                 (evil-visual-state . ,my/visual-leader-map)))
        (funcall (car state-and-leader))
        (should (eq (key-binding (kbd "SPC")) (cdr state-and-leader)))
        (should (eq (key-binding (kbd "SPC l")) 'display-line-numbers-mode))
        (should (eq (key-binding (kbd "SPC g g")) 'magit-status))
        (should (eq (key-binding (kbd "S-SPC"))
                    'magit-diff-show-or-scroll-up)))
      (dolist (state '(evil-insert-state evil-emacs-state))
        (funcall state)
        (should (eq (key-binding (kbd "SPC"))
                    (cdr mode-and-native-space)))))
  (with-temp-buffer
    (magit-status-mode)
    (evil-normal-state)
    (unwind-protect
        (progn
          (call-interactively #'magit-dispatch)
          (should (eq (key-binding (kbd "s")) 'magit-stage)))
      (when (bound-and-true-p transient--prefix)
        (transient-quit-one))))))

(ert-deftest my/leader-bindings-diff-hl-workflow ()
  (require 'diff-hl)
  (require 'diff-hl-show-hunk)
  (should-not diff-hl-show-staged-changes)
  (should-not diff-hl-highlight-reference-function)
  (should diff-hl-ask-before-revert-hunk)
  (should-not auto-revert-remote-files)
  (should-not diff-hl-disable-on-remote)
  (dolist (binding '(("g p" . diff-hl-show-hunk)
                     ("g s" . diff-hl-stage-current-hunk)
                     ("g r" . diff-hl-revert-hunk)
                     ("g a" . my/annotate-current-hunk)
                     ("r v" . my/annotations-show)))
    (should (eq (keymap-lookup my/leader-map (car binding))
                (cdr binding))))
  (with-temp-buffer
    (diff-hl-mode 1)
    (evil-normal-state)
    (evil-normalize-keymaps)
    (should (eq (key-binding (kbd "[h")) #'diff-hl-previous-hunk))
    (should (eq (key-binding (kbd "]h")) #'diff-hl-next-hunk))
    (diff-hl-mode -1)
    (evil-normal-state)
    (evil-normalize-keymaps)
    (should-not (eq (key-binding (kbd "[h")) #'diff-hl-previous-hunk))
    (should-not (eq (key-binding (kbd "]h")) #'diff-hl-next-hunk)))
  (should (eq (keymap-lookup diff-hl-show-hunk-map "r")
              #'my/diff-hl-preview-revert-hunk))
  (dolist (binding '(("p" . diff-hl-show-hunk-previous)
                     ("n" . diff-hl-show-hunk-next)
                     ("e" . diff-hl-show-hunk-ediff)
                     ("c" . diff-hl-show-hunk-copy-original-text)
                     ("S" . diff-hl-show-hunk-stage-hunk)))
    (should (eq (keymap-lookup diff-hl-show-hunk-map (car binding))
                (cdr binding))))
  (let (calls)
    (let ((diff-hl-ask-before-revert-hunk t))
      (cl-letf (((symbol-function 'diff-hl-show-hunk-hide)
                 (lambda () (push 'hide calls)))
                ((symbol-function 'diff-hl-revert-hunk)
                 (lambda ()
                   (push (if diff-hl-ask-before-revert-hunk
                             'confirmed
                           'unconfirmed)
                         calls))))
        (my/diff-hl-preview-revert-hunk)))
    (should (equal (nreverse calls) '(hide confirmed)))))

(ert-deftest my/leader-bindings-send-text-integration ()
  (should (eq (keymap-lookup my/leader-map "t r")
              #'my/send-region-or-buffer-to-last-target))
  (should (eq (keymap-lookup my/leader-map "t R")
              #'my/send-region-or-buffer))
  (should (eq (keymap-lookup my/leader-map "t g")
              #'my/create-ghostel-terminal-in-split))
  (should (eq (keymap-lookup my/leader-map "t z")
              #'my/open-or-create-zmx-session-in-split))
  (should (eq (lookup-key evil-visual-state-map (kbd "C-c C-c"))
              #'my/send-region-or-buffer))
  (should (eq (lookup-key evil-visual-state-map (kbd "C-c C-r"))
              #'my/send-region-or-buffer-to-last-target)))

(ert-deftest my/leader-bindings-workflow-commands ()
  (with-temp-buffer
    (dolist (state '(evil-normal-state evil-visual-state))
      (funcall state)
      (should (eq (key-binding (kbd "SPC o w")) #'my/work-start))
      (should (eq (key-binding (kbd "SPC o W"))
                  #'markdown-table-wrap-pretty-toggle))
      (should (eq (key-binding (kbd "SPC o l")) #'my/work-log))
      (should (eq (key-binding (kbd "SPC o u")) #'my/work-draft-update)))))

(ert-deftest my/leader-bindings-ghostel-insert-state-escape-hatches ()
  (let ((shared-window-bindings
         '(("h" . evil-window-left)
           ("j" . evil-window-down)
           ("k" . evil-window-up)
           ("l" . evil-window-right)
           ("v" . evil-window-vsplit)
           ("%" . evil-window-vsplit)
           ("s" . evil-window-split)
           ("\"" . evil-window-split)
           ("H" . evil-window-decrease-width)
           ("J" . evil-window-increase-height)
           ("K" . evil-window-decrease-height)
           ("L" . evil-window-increase-width)
           ("q" . delete-window)
           ("x" . window-swap-states)
           ("=" . balance-windows)
           ("|" . maximize-window)
           ("z" . delete-other-windows)
           ("u" . winner-undo)
           ("r" . winner-redo)
           ("t c" . tab-bar-new-tab)
           ("t q" . tab-bar-close-tab)
           ("t [" . tab-bar-switch-to-prev-tab)
           ("t ]" . tab-bar-switch-to-next-tab))))
    (should evil-vsplit-window-right)
    (should evil-split-window-below)
    (with-temp-buffer
      (fundamental-mode)
      (dolist (state '(evil-normal-state evil-visual-state))
        (funcall state)
        (should (eq (key-binding (kbd "C-b")) my/editor-window-map))
        (should (eq (key-binding (kbd "C-b C-b")) #'evil-scroll-page-up))
        (dolist (binding shared-window-bindings)
          (should (eq (key-binding (kbd (concat "SPC w " (car binding))))
                      (cdr binding)))
          (should (eq (key-binding (kbd (concat "C-b " (car binding))))
                      (cdr binding)))))
      (evil-insert-state)
      (should (eq (key-binding (kbd "C-b")) #'backward-char))
      (evil-emacs-state)
      (should (eq (key-binding (kbd "C-b")) #'backward-char)))
  (with-temp-buffer
    (ghostel-mode)
    (evil-ghostel-mode 1)
    (unwind-protect
        (progn
          (dolist (state '(evil-normal-state evil-visual-state))
            (funcall state)
            (should (eq (key-binding (kbd "C-b")) my/editor-window-map))
            (should (eq (key-binding (kbd "C-b C-b"))
                        #'evil-scroll-page-up))
            (dolist (binding shared-window-bindings)
              (should (eq (key-binding (kbd (concat "C-b " (car binding))))
                          (cdr binding)))))
          (ghostel-semi-char-mode)
          (evil-insert-state)
          (should (eq (key-binding (kbd "C-b")) my/terminal-window-map))
          (should (eq (key-binding (kbd "M-SPC")) my/leader-map))
          (dolist (binding shared-window-bindings)
            (should (eq (key-binding (kbd (concat "C-b " (car binding))))
                        (cdr binding))))
          (should (eq (key-binding (kbd "M-SPC w z"))
                      (keymap-lookup my/leader-map "w z")))
          (let (sent-keys)
            (cl-letf (((symbol-function 'ghostel-send-key)
                       (lambda (&rest args)
                         (push args sent-keys))))
              (call-interactively (key-binding (kbd "C-b C-b"))))
            (should (equal sent-keys '(("b" "ctrl")))))
          (ghostel-char-mode)
          (should (eq (key-binding (kbd "C-b")) #'ghostel--send-event))
          (should (eq (key-binding (kbd "M-SPC")) #'ghostel--send-event))
          (should (eq (key-binding (kbd "M-RET")) #'ghostel-semi-char-mode))
          (should-not (key-binding (kbd "C-b h")))
          (should-not (key-binding (kbd "M-SPC w z")))
          (let ((prepared-buffer (current-buffer))
                (entry '(:name "state-test" :directory "/tmp/")))
            (ghostel-semi-char-mode)
            (evil-normal-state)
            (cl-letf (((symbol-function 'term-sessions-open)
                       (lambda (&rest _) (set-buffer prepared-buffer))))
              (my/open-or-create-zmx-session-in-split entry))
            (should (eq ghostel--input-mode 'semi-char))
            (should (eq evil-state 'insert))
            (call-interactively (key-binding (kbd "s-<escape>")))
            (should (eq ghostel--input-mode 'semi-char))
            (should (eq evil-state 'normal))
            (ghostel-char-mode)
            (should (eq ghostel--input-mode 'char))
            (cl-letf (((symbol-function 'term-sessions-open)
                       (lambda (&rest _) (set-buffer prepared-buffer))))
              (my/open-or-create-zmx-session-in-split entry))
            (should (eq ghostel--input-mode 'semi-char))
            (should (eq evil-state 'insert))
            (let (ready-position)
              (cl-letf (((symbol-function 'term-sessions-open)
                         (lambda (&rest _) (set-buffer prepared-buffer)))
                        ((symbol-function 'evil-ghostel--prompt-active-p)
                         (lambda () t))
                        ((symbol-function 'evil-ghostel-goto-input-position)
                         (lambda (position) (setq ready-position position))))
                (setq-local ghostel--cursor-pos nil)
                (evil-normal-state)
                (my/open-or-create-zmx-session-in-split entry)
                (should (eq evil-state 'insert))
                (should-not ready-position)
                (setq-local ghostel--cursor-pos '(0 . 0)
                            ghostel--term-rows 1)
                (evil-normal-state)
                (my/open-or-create-zmx-session-in-split entry)
                (should (eq evil-state 'insert))
                (should (= ready-position (point)))))))
      (evil-ghostel-mode -1)))
  (with-temp-buffer
    (fundamental-mode)
    (evil-insert-state)
    (should (eq (key-binding (kbd "C-b")) #'backward-char))
    (should (eq (key-binding (kbd "M-SPC")) #'cycle-spacing)))
  (with-current-buffer (get-buffer " *Minibuf-0*")
    (should (minibufferp))
    (should (eq (key-binding (kbd "C-b")) #'backward-char)))
  (let ((init-file (expand-file-name "init.el" my/config-directory))
        (initial-shared-window-map (keymap-lookup my/leader-map "w"))
        (initial-editor-window-map my/editor-window-map)
        (initial-terminal-window-map my/terminal-window-map))
    (load init-file nil nil nil t)
    (let ((first-shared-window-map (keymap-lookup my/leader-map "w"))
          (first-editor-window-map my/editor-window-map)
          (first-terminal-window-map my/terminal-window-map))
      (should-not (eq first-shared-window-map initial-shared-window-map))
      (should-not (eq first-editor-window-map initial-editor-window-map))
      (should-not (eq first-terminal-window-map initial-terminal-window-map))
      (load init-file nil nil nil t)
      (should-not (eq (keymap-lookup my/leader-map "w")
                      first-shared-window-map))
      (should-not (eq my/editor-window-map first-editor-window-map))
      (should-not (eq my/terminal-window-map first-terminal-window-map))
      (should (eq (keymap-parent my/editor-window-map)
                  (keymap-lookup my/leader-map "w")))
      (should (eq (keymap-parent my/terminal-window-map)
                  (keymap-lookup my/leader-map "w")))
      (with-temp-buffer
        (fundamental-mode)
        (evil-normal-state)
        (should (eq (key-binding (kbd "C-b")) my/editor-window-map)))))))

;;; leader-bindings-test.el ends here
