;;; markdown-parity-test.el --- Markdown parity behavior tests -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)

(load (expand-file-name "init.el" (file-name-directory (or load-file-name buffer-file-name)))
      nil nil nil t)
(require 'markdown-ts-mode)

(defun my/markdown-test-before-p (text first second)
  "Return non-nil when FIRST appears before SECOND in TEXT."
  (let ((first-position (string-match (regexp-quote first) text))
        (second-position (string-match (regexp-quote second) text)))
    (and first-position second-position (< first-position second-position))))

(ert-deftest my/markdown-parity-structural-behavior ()
  (dolist (mode '(markdown-ts-mode markdown-mode))
    (with-temp-buffer
      (insert "# first\n\n# second\n")
      (funcall mode)
      (goto-char (point-min))
      (search-forward "# second")
      (beginning-of-line)
      (my/markdown-move-up)
      (should (my/markdown-test-before-p (buffer-string) "# second" "# first"))
      (my/markdown-move-down)
      (should (my/markdown-test-before-p (buffer-string) "# first" "# second"))
      (goto-char (point-min))
      (my/markdown-demote)
      (should (string-match-p "## first" (buffer-string)))
      (my/markdown-promote)
      (should-not (string-match-p "## first" (buffer-string))))
    (with-temp-buffer
      (insert "- parent\n- child\n")
      (funcall mode)
      (goto-char (point-min))
      (my/markdown-move-down)
      (should (my/markdown-test-before-p (buffer-string) "- child" "- parent")))
    (with-temp-buffer
      (insert "- parent\n- child\n")
      (funcall mode)
      (goto-char (point-min))
      (search-forward "child")
      (beginning-of-line)
      (my/markdown-move-up)
      (should (my/markdown-test-before-p (buffer-string) "- child" "- parent")))
    (with-temp-buffer
      (insert "- parent\n- child\n")
      (funcall mode)
      (goto-char (point-min))
      (search-forward "child")
      (beginning-of-line)
      (my/markdown-demote)
      (should (string-match-p "^[ \t]+- child" (buffer-string)))
      (my/markdown-promote)
      (should-not (string-match-p "^[ \t]+- child" (buffer-string))))
    (with-temp-buffer
      (insert "| First | Second |\n| ----- | ------ |\n| one | two |\n| three | four |\n")
      (funcall mode)
      (goto-char (point-min))
      (search-forward "one")
      (search-backward "one")
      (my/markdown-move-down)
      (should (my/markdown-test-before-p (buffer-string) "three" "one"))
      (goto-char (point-min))
      (search-forward "one")
      (search-backward "one")
      (my/markdown-move-up)
      (should (my/markdown-test-before-p (buffer-string) "one" "three"))
      (goto-char (point-min))
      (search-forward "one")
      (search-backward "one")
      (my/markdown-demote)
      (should (my/markdown-test-before-p (buffer-string) "Second" "First"))
      (goto-char (point-min))
      (search-forward "one")
      (search-backward "one")
      (my/markdown-promote)
      (should (my/markdown-test-before-p (buffer-string) "First" "Second")))))

(ert-deftest my/markdown-parity-access-and-binding-scope ()
  (let (normal-tab normal-control-i)
    (with-temp-buffer
      (evil-normal-state)
      (setq normal-tab (key-binding (kbd "TAB"))
            normal-control-i (key-binding (kbd "C-i"))))
    (dolist (mode '(markdown-ts-mode markdown-mode))
      (with-temp-buffer
        (funcall mode)
        (dolist (state '(evil-normal-state evil-visual-state))
          (funcall state)
          (dolist (binding '(("M-h" . my/markdown-promote)
                             ("M-j" . my/markdown-move-down)
                             ("M-k" . my/markdown-move-up)
                             ("M-l" . my/markdown-demote)
                             ("g TAB" . my/markdown-cycle)
                             ("g <tab>" . my/markdown-cycle)
                             ("g S-TAB" . my/markdown-cycle-buffer)
                             ("g <backtab>" . my/markdown-cycle-buffer)
                             ("C-x n s" . my/markdown-narrow-to-subtree)
                             ("SPC o m" . my/markdown-align-table)
                             ("SPC o RET" . my/send-markdown-fenced-code-to-last-target)
                             ("SPC t b" . my/send-markdown-fenced-code-to-last-target)
                             ("SPC t B" . my/send-markdown-fenced-code-to-target)))
            (should (eq (key-binding (kbd (car binding))) (cdr binding)))))
        (evil-normal-state)
        (should (eq (key-binding (kbd "TAB")) normal-tab))
        (should (eq (key-binding (kbd "C-i")) normal-control-i)))
      (with-temp-buffer
        (insert "# first\nbody\n## child\nchild body\n# second\nsecond body\n")
        (funcall mode)
        (evil-normal-state)
        (goto-char (point-min))
        (search-forward "body")
        (call-interactively (key-binding (kbd "g TAB")))
        (forward-line 1)
        (should (outline-invisible-p (point)))
        (outline-show-all)
        (goto-char (point-min))
        (search-forward "child body")
        (call-interactively (key-binding (kbd "C-x n s")))
        (should (buffer-narrowed-p))
        (should-not (string-match-p "# second" (buffer-string)))
        (widen)
        (should (string-match-p "# second" (buffer-string))))
      (with-temp-buffer
        (insert "|First|Second|\n|---|---|\n|one|two|\n|three|four|\n")
        (funcall mode)
        (evil-normal-state)
        (goto-char (point-min))
        (search-forward "one")
        (search-backward "one")
        (when (eq mode 'markdown-ts-mode)
          (markdown-ts-in-table-mode 1))
        (should (eq (key-binding (kbd "TAB")) #'evil-jump-forward))
        (should (eq (key-binding (kbd "C-i")) #'evil-jump-forward))
        (should (eq (key-binding (kbd "<tab>")) #'evil-jump-forward))
        (let ((start (point)))
          (call-interactively (key-binding (kbd "g TAB")))
          (should (/= start (point))))
        (goto-char (point-min))
        (search-forward "one")
        (search-backward "one")
        (let ((start (point)))
          (call-interactively (key-binding (kbd "g S-TAB")))
          (should (/= start (point))))
        (goto-char (point-min))
        (search-forward "one")
        (search-backward "one")
        (let ((start (point)))
          (call-interactively (key-binding (kbd "g <tab>")))
          (should (/= start (point))))
        (goto-char (point-min))
        (search-forward "one")
        (search-backward "one")
        (let ((start (point)))
          (call-interactively (key-binding (kbd "g <backtab>")))
          (should (/= start (point))))
        (let ((command (if (eq mode 'markdown-ts-mode)
                           'markdown-ts-table-align-table
                         'markdown-table-align))
              called)
          (cl-letf (((symbol-function command)
                     (lambda () (interactive) (setq called t))))
            (call-interactively (key-binding (kbd "SPC o m"))))
          (should called)))
      (with-temp-buffer
        (insert "# not a table\n")
        (funcall mode)
        (should-error (my/markdown-align-table) :type 'user-error))))
  (with-temp-buffer
    (org-mode)
    (evil-normal-state)
    (should (eq (key-binding (kbd "SPC o RET")) #'org-babel-execute-src-block))
    (should (eq (key-binding (kbd "SPC t R")) #'my/send-region-or-buffer)))
  (with-temp-buffer
    (evil-visual-state)
    (should (eq (key-binding (kbd "C-c C-c")) #'my/send-region-or-buffer))
    (should (eq (key-binding (kbd "C-c C-r"))
                #'my/send-region-or-buffer-to-last-target))))

(ert-deftest my/markdown-parity-fenced-code-extraction-and-delivery ()
  (dolist (mode '(markdown-ts-mode markdown-mode))
    (dolist (fixture '(("```python title\nprint(1)\nprint(2)\n```\n"
                        . "print(1)\nprint(2)\n")
                       ("~~~sh\necho tilde\n~~~\n" . "echo tilde\n")
                       ("```sh\n```\n" . "")
                       ("~~~\n~~~\n" . "")))
      (with-temp-buffer
        (insert (car fixture))
        (funcall mode)
        (goto-char (point-min))
        (unless (string-empty-p (cdr fixture))
          (forward-line 1))
        (should (equal (my/markdown-fenced-code-body) (cdr fixture)))))
    (dolist (fixture '("plain text\n"
                       "---\ntitle: metadata\n---\n"
                       "```python\nprint(1)\n"))
      (with-temp-buffer
        (insert fixture)
        (funcall mode)
        (should-error (my/markdown-fenced-code-body) :type 'user-error)))
    (with-temp-buffer
      (insert "```sh\necho sent\n```\n")
      (funcall mode)
      (goto-char (point-min))
      (forward-line 1)
      (let (replayed chosen)
        (cl-letf (((symbol-function 'my/send-text-send-to-last-target)
                   (lambda (text) (setq replayed text)))
                  ((symbol-function 'my/send-text-to-target)
                   (lambda (text) (setq chosen text))))
          (my/send-markdown-fenced-code-to-last-target)
          (my/send-markdown-fenced-code-to-target))
        (should (equal replayed "echo sent\n"))
        (should (equal chosen "echo sent\n"))))))

;;; markdown-parity-test.el ends here
