;;; my-workflow-test.el --- Tests for project-partitioned Org work items -*- lexical-binding: t; -*-

;;; Code:

(require 'cl-lib)
(require 'ert)
(require 'org)

(add-to-list 'load-path
             (file-name-directory (or load-file-name buffer-file-name)))
(require 'my-workflow)

(defmacro my/workflow-test-with-storage (&rest body)
  "Run BODY with isolated Org and workflow storage."
  (declare (indent 0) (debug t))
  `(let* ((temporary-root (make-temp-file "my-workflow-test-" t))
          (workspace (expand-file-name "workspace/" temporary-root))
          (workspace-two (expand-file-name "workspace-two/" temporary-root))
          (workspace-three (expand-file-name "workspace-three/" temporary-root))
          (my/workflow-project-storage-root
           (expand-file-name "projects/" temporary-root))
          (my/workflow-journal-file (expand-file-name "journal.org" temporary-root))
          (my/workflow-life-file (expand-file-name "life.org" temporary-root))
          (org-directory temporary-root)
          (org-id-locations nil)
          (org-id-locations-file (expand-file-name ".org-id-locations" temporary-root))
          (org-agenda-files nil)
          (default-directory temporary-root))
     (make-directory workspace t)
     (make-directory workspace-two t)
     (make-directory workspace-three t)
     (unwind-protect
         (progn ,@body)
       (dolist (buffer (buffer-list))
         (when (and (buffer-file-name buffer)
                    (string-prefix-p temporary-root (buffer-file-name buffer)))
           (set-buffer-modified-p nil)
           (kill-buffer buffer)))
       (delete-directory temporary-root t))))

(defmacro my/workflow-test-with-tabs (&rest body)
  "Run BODY with a public tab-bar API model and no real frame state."
  (declare (indent 0) (debug t))
  `(let ((tabs (list '(current-tab (name . "first")
                            (my/send-text-last-target . kept)))))
     (cl-letf
         (((symbol-function 'tab-bar-tabs)
           (lambda (&optional _frame) tabs))
          ((symbol-function 'tab-bar-tabs-set)
           (lambda (new-tabs &optional _frame) (setq tabs new-tabs)))
          ((symbol-function 'tab-bar-new-tab)
           (lambda (&optional _frame)
             (setq tabs
                   (append
                    (mapcar (lambda (tab)
                              (if (eq (car tab) 'current-tab)
                                  (cons 'tab (cdr tab))
                                tab))
                            tabs)
                    (list '(current-tab (name . "new")))))))
          ((symbol-function 'tab-bar-select-tab)
           (lambda (index &optional _frame)
             (setq tabs
                   (cl-loop for tab in tabs
                            for tab-index from 1
                            collect (cons (if (= index tab-index) 'current-tab 'tab)
                                          (cdr tab)))))))
       ,@body)))

(defun my/workflow-test-file-text (file)
  "Return FILE's complete contents for behavior assertions."
  (with-temp-buffer
    (insert-file-contents file)
    (buffer-string)))

(defun my/workflow-test-count (regexp text)
  "Return the count of REGEXP matches in TEXT."
  (let ((start 0)
        (count 0))
    (while (string-match regexp text start)
      (setq count (1+ count)
            start (match-end 0)))
    count))

(ert-deftest my/workflow-root-and-tab-contract ()
  (my/workflow-test-with-tabs
    (let ((first "/tmp/one/")
          (second "/tmp/two/"))
      (cl-letf (((symbol-function 'project-current)
                 (lambda (_maybe-prompt directory)
                   (when (string-prefix-p "/tmp/one" directory) 'project)))
                ((symbol-function 'project-root)
                 (lambda (_project) "/tmp/project")))
        (should (equal (my/workspace-normalize-root "/tmp/one/file/" )
                       "/tmp/project/"))
        (should (equal (my/workspace-normalize-root "/ssh:build:/srv/work")
                       "/ssh:build:/srv/work/")))
      (my/workspace-select-or-create-tab first)
      (my/tab-set-current-property 'my/work-task-id "task-one")
      (should (equal (my/workspace-tab-index first) 2))
      (should (equal (my/tab-find-index-by-property 'my/work-task-id "task-one") 2))
      (should (equal (my/tab-current-property 'my/send-text-last-target) nil))
      (my/workspace-select-or-create-tab second)
      (should (equal (my/workspace-tab-index second) 3))
      (my/tab-set-current-property 'my/work-task-id nil)
      (should-not (my/tab-current-property 'my/work-task-id)))))

(ert-deftest my/workflow-start-schema-journal-and-resume ()
  (my/workflow-test-with-storage
    (my/workflow-test-with-tabs
      (cl-letf (((symbol-function 'my/workflow-open-task) (lambda (task) task)))
        (let* ((first (my/work-start "Ship parser" workspace "compiler" "parser"))
               (second (my/work-start "Ship parser" workspace-two "runtime" "parser"))
               (first-index (my/workflow-project-index-file "compiler"))
               (second-index (my/workflow-project-index-file "runtime")))
          (should (file-exists-p first-index))
          (should (file-exists-p second-index))
          (should (plist-get first :id))
          (should-not (equal (plist-get first :id) (plist-get second :id)))
          (should (equal (plist-get first :key) "parser"))
          (should (equal (plist-get second :key) "parser"))
          (should (member first-index org-agenda-files))
          (should (member second-index org-agenda-files))
          (let ((first-text (my/workflow-test-file-text first-index))
                (journal (my/workflow-test-file-text my/workflow-journal-file)))
            (should (string-match-p (regexp-quote "** Docs\n\n** Tasks\n") first-text))
            (should (string-match-p ":ID:" first-text))
            (should (string-match-p ":WORK_KEY: parser" first-text))
            (should-not (string-match-p "LINEAR_\\|:linear:" first-text))
            (should (= (my/workflow-test-count "Work log" journal) 1))
            (should (string-match-p (regexp-quote (concat "[[id:" (plist-get first :id)))
                                    journal))
            (should (string-match-p (regexp-quote "[compiler/parser]") journal))
            (should (string-match-p (regexp-quote "[runtime/parser]") journal)))
          (my/work-start "Ship parser" workspace "compiler" "parser")
          (let ((schema (my/workflow-project-schema (find-file-noselect first-index))))
            (should (= (length (my/workflow-tasks schema)) 1)))
          (should (= (my/workflow-test-count "start:" (my/workflow-test-file-text
                                                     my/workflow-journal-file))
                     2)))))))

(ert-deftest my/workflow-start-interactive-selection-binds-unbound-tab ()
  (my/workflow-test-with-storage
    (my/workflow-test-with-tabs
      (cl-letf (((symbol-function 'my/workflow-open-task) (lambda (task) task)))
        (let ((task (my/work-start "Existing task" workspace "alpha" "existing")))
          (my/tab-set-current-property 'my/work-task-id nil)
          (cl-letf (((symbol-function 'my/workflow-read-project-key)
                     (lambda (_root) "alpha"))
                    ((symbol-function 'called-interactively-p)
                     (lambda (&rest _arguments) t))
                    ((symbol-function 'completing-read)
                     (lambda (_prompt collection &rest _arguments)
                       (cadr collection))))
            (let ((default-directory workspace))
              (call-interactively #'my/work-start)))
          (should (equal (my/tab-current-property 'my/work-task-id)
                         (plist-get task :id)))
          (should (= (my/workflow-test-count
                      "start:"
                      (my/workflow-test-file-text my/workflow-journal-file))
                     1)))))))

(ert-deftest my/workflow-discovery-is-canonical-and-collision-safe ()
  (my/workflow-test-with-storage
    (let* ((schema (my/workflow-ensure-project "alpha" workspace))
           (index (my/workflow-project-index-file "alpha"))
           (notes (expand-file-name "notes/extra.org"
                                    (file-name-directory index)))
           (flat (expand-file-name "alpha.org" my/workflow-project-storage-root))
           (shared (expand-file-name "shared.org" my/workflow-project-storage-root))
           (broken (expand-file-name "broken/" my/workflow-project-storage-root))
           (duplicate (expand-file-name "duplicate/" my/workflow-project-storage-root)))
      (make-directory (file-name-directory notes) t)
      (with-temp-file notes (insert "* Auxiliary\n"))
      (with-temp-file flat (insert "* Flat\n"))
      (with-temp-file shared (insert "* Shared\n"))
      (make-directory broken t)
      (make-directory duplicate t)
      (with-temp-file (expand-file-name "index.org" broken)
        (insert "* broken\n:PROPERTIES:\n:ID: broken\n:PROJECT_KEY: broken\n"
                ":PROJECT_ROOT: /tmp/broken/\n:END:\n\n** Docs\n\n** Tasks\n"
                "*** Active\n\n** Log\n"))
      (with-temp-file (expand-file-name "index.org" duplicate)
        (insert "* duplicate\n:PROPERTIES:\n:ID: duplicate\n:PROJECT_KEY: duplicate\n"
                ":PROJECT_ROOT: /tmp/duplicate/\n:END:\n\n** Docs\n\n** Docs\n\n"
                "** Tasks\n*** Active\n\n*** Archive :ARCHIVE:\n\n** Log\n"))
      (with-temp-file my/workflow-life-file (insert "* Life\n"))
      (should (equal (my/workflow-discover-project-indexes) (list index)))
      (my/workflow-refresh-agenda)
      (should (equal org-agenda-files (list my/workflow-life-file index)))
      (should-not (member notes org-agenda-files))
      (should-not (member flat org-agenda-files))
      (should-not (member shared org-agenda-files))
      (should-not (member (expand-file-name "index.org" broken) org-agenda-files))
      (should-not (member (expand-file-name "index.org" duplicate) org-agenda-files))
      (with-current-buffer (find-file-noselect index)
        (save-excursion
          (goto-char (plist-get schema :docs))
          (org-end-of-subtree t)
          (insert "\n- [[file:reference.md][Reference]]\n")
          (goto-char (plist-get schema :tasks))
          (org-end-of-subtree t)
          (insert "\n*** Backlog\n")
          (goto-char (plist-get schema :project))
          (org-end-of-subtree t)
          (insert "\n** Notes\n")
          (save-buffer)))
      (setq schema (my/workflow-project-schema (find-file-noselect index)))
      (should schema)
      (with-current-buffer (find-file-noselect index)
        (save-excursion
          (goto-char (plist-get schema :active))
          (org-end-of-subtree t)
          (insert "\n**** Plain heading\n:PROPERTIES:\n:ID: not-a-task\n:END:\n")
          (save-buffer)))
      (should-not (my/workflow-tasks schema))
      (dolist (key '("" "." ".." "nested/key" "/absolute" "nested\\key"))
        (should-error (my/workflow-project-index-file key) :type 'user-error))
      (should-error (my/workflow-ensure-project "broken" workspace) :type 'user-error)
      (with-current-buffer (find-file-noselect index)
        (goto-char (point-min))
        (re-search-forward ":PROJECT_KEY: alpha")
        (replace-match ":PROJECT_KEY: wrong")
        (save-buffer))
      (let ((before (my/workflow-test-file-text index)))
        (should-error (my/workflow-ensure-project "alpha" workspace) :type 'user-error)
        (should (equal (my/workflow-test-file-text index) before)))
      (should (plist-get schema :id)))))

(ert-deftest my/workflow-lifecycle-project-log-note-archive-and-draft ()
  (my/workflow-test-with-storage
    (my/workflow-test-with-tabs
      (cl-letf (((symbol-function 'my/workflow-open-task) (lambda (task) task)))
        (let* ((task (my/work-start "Refine lexer" workspace "compiler" "lexer"))
               (index (my/workflow-project-index-file "compiler"))
               (note (expand-file-name "detail.md" temporary-root))
               (invalid-note (expand-file-name "detail.txt" temporary-root)))
          (with-temp-file note (insert "# Detail\n"))
          (with-temp-file invalid-note (insert "not a note\n"))
          (should-error (my/work-bind-note invalid-note) :type 'user-error)
          (should-not (plist-get task :note-file))
          (cl-letf (((symbol-function 'my/work-open) (lambda () nil)))
            (my/work-bind-note note))
          (my/work-log 'progress "Tests are green.")
          (my/work-project-log "Reviewed parser edge cases.")
          (my/work-set-state "DONE")
          (my/work-archive)
          (let ((schema (my/workflow-project-schema (find-file-noselect index))))
            (should-not (my/workflow-tasks schema))
            (should (equal (plist-get (car (my/workflow-tasks schema t)) :id)
                           (plist-get task :id))))
          (let ((journal (my/workflow-test-file-text my/workflow-journal-file))
                (project (my/workflow-test-file-text index)))
            (should (string-match-p "progress: Tests are green\." journal))
            (should (string-match-p (regexp-quote "[[file:") journal))
            (should (string-match-p "Reviewed parser edge cases\." project))
            (should-not (string-match-p "Reviewed parser edge cases\." journal)))
          (should (equal (my/workflow-sanitize-draft-text
                          ":PROPERTIES:\n:ID: hidden\n:END:\n[[file:/tmp/private.md][Detail]]")
                         "Detail"))
          (should (my/workflow-draft-sensitive-p "token=abc /tmp/private")))))))

(ert-deftest my/workflow-failure-order-and-start-retry-idempotence ()
  (my/workflow-test-with-storage
    (my/workflow-test-with-tabs
      (cl-letf (((symbol-function 'my/workflow-open-task) (lambda (task) task)))
        (cl-letf (((symbol-function 'my/workflow-append-journal-entry)
                   (lambda (&rest _) (error "journal failed"))))
          (should-error (my/work-start "Reusable task" workspace "alpha" "reuse")))
        (let ((index (my/workflow-project-index-file "alpha")))
          (should (file-exists-p index))
          (should-not (file-exists-p my/workflow-journal-file))
          (should-not (my/workspace-tab-index workspace))
          (cl-letf (((symbol-function 'my/workspace-select-or-create-tab)
                     (lambda (_root) (error "tab commit interrupted"))))
            (should-error (my/work-start "Reusable task" workspace "alpha" "reuse")))
          (let ((task (my/workflow-find-task-by-key
                       (my/workflow-project-schema (find-file-noselect index)) "reuse")))
            (should task)
            (should (= (my/workflow-test-count
                        (regexp-quote (concat "[[id:" (plist-get task :id)))
                        (my/workflow-test-file-text my/workflow-journal-file))
                       1)))
          (my/work-start "Reusable task" workspace "alpha" "reuse")
          (let ((task (my/workflow-find-task-by-key
                       (my/workflow-project-schema (find-file-noselect index)) "reuse")))
            (should (equal (my/tab-current-property 'my/work-task-id)
                           (plist-get task :id)))
            (should (= (my/workflow-test-count
                        (regexp-quote (concat "[[id:" (plist-get task :id)))
                        (my/workflow-test-file-text my/workflow-journal-file))
                       1))))))))

(ert-deftest my/workflow-start-preflight-and-tab-rollback ()
  (my/workflow-test-with-storage
    (my/workflow-test-with-tabs
      (cl-letf (((symbol-function 'my/workflow-open-task) (lambda (task) task)))
        (let ((index (my/workflow-project-index-file "new-project"))
              (before-tabs (copy-tree tabs))
              (before-agenda (copy-sequence org-agenda-files))
              (invalid-note (expand-file-name "invalid.txt" temporary-root)))
          (with-temp-file invalid-note (insert "not a detail note\n"))
          (dolist (arguments
                   (list (list "Bad\ntitle" workspace "new-project" "new-task")
                         (list "Good title" workspace "new\nproject" "new-task")
                         (list "Good title" workspace "new-project" "new\rkey")
                         (list "Good title" workspace "new-project" "new-task"
                               invalid-note)))
            (should-error (apply #'my/work-start arguments) :type 'user-error)
            (should-not (file-exists-p index))
            (should (equal org-agenda-files before-agenda))
            (should (equal tabs before-tabs)))
          (my/workspace-select-or-create-tab workspace)
          (my/tab-set-current-property 'my/work-task-id "another-task")
          (setq before-tabs (copy-tree tabs)
                before-agenda (copy-sequence org-agenda-files))
          (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _arguments) nil)))
            (should-error (my/work-start "Rejected tab rebind" workspace
                                         "new-project" "new-task")
                          :type 'user-error))
          (should-not (file-exists-p index))
          (should (equal org-agenda-files before-agenda))
          (should (equal tabs before-tabs))
          (should (eq (alist-get 'my/send-text-last-target (cdr (car tabs))) 'kept)))
      (let* ((task (my/work-start "Existing task" workspace-two "alpha" "existing"))
             (index (my/workflow-project-index-file "alpha"))
             (before-project (my/workflow-test-file-text index))
             (before-journal (my/workflow-test-file-text my/workflow-journal-file))
             (before-tabs (copy-tree tabs))
             (before-agenda (copy-sequence org-agenda-files))
             (answers '(t nil)))
        (cl-letf (((symbol-function 'y-or-n-p)
                   (lambda (&rest _arguments) (pop answers))))
          (should-error (my/work-start "Existing task" workspace "alpha" "existing")
                        :type 'user-error))
        (should (equal (my/workflow-test-file-text index) before-project))
        (should (equal (my/workflow-test-file-text my/workflow-journal-file)
                       before-journal))
        (should (equal org-agenda-files before-agenda))
        (should (equal tabs before-tabs))
        (should (equal (plist-get task :id)
                       (plist-get (my/workflow-find-task-by-key
                                   (my/workflow-project-schema (find-file-noselect index))
                                   "existing")
                                  :id))))
      (let ((before-tabs (copy-tree tabs))
            original-tab-set)
        (setq original-tab-set (symbol-function 'my/tab-set-current-property))
        (cl-letf (((symbol-function 'my/tab-set-current-property)
                   (lambda (property value)
                     (if (eq property 'my/work-task-id)
                         (error "task-id commit failed")
                       (funcall original-tab-set property value)))))
          (should-error (my/work-start "Rollback task" workspace-three
                                       "rollback" "rollback-task")))
        (should (equal tabs before-tabs))
        (should (eq (alist-get 'my/send-text-last-target (cdr (car tabs))) 'kept))
        (let* ((index (my/workflow-project-index-file "rollback"))
               (schema (my/workflow-project-schema (find-file-noselect index)))
               (task (my/workflow-find-task-by-key schema "rollback-task"))
               (journal (my/workflow-test-file-text my/workflow-journal-file)))
          (should task)
          (should (= (my/workflow-test-count
                      (regexp-quote (concat "[[id:" (plist-get task :id))) journal)
                     1))
          (my/work-start "Rollback task" workspace-three "rollback" "rollback-task")
          (should (= (my/workflow-test-count
                      (regexp-quote (concat "[[id:" (plist-get task :id)))
                      (my/workflow-test-file-text my/workflow-journal-file))
                     1))))))))

(ert-deftest my/workflow-one-line-inputs-and-duplicate-work-log ()
  (my/workflow-test-with-storage
    (my/workflow-test-with-tabs
      (cl-letf (((symbol-function 'my/workflow-open-task) (lambda (task) task)))
        (let* ((task (my/work-start "Input validation" workspace "alpha" "input"))
               (index (my/workflow-project-index-file "alpha"))
               (before-project (my/workflow-test-file-text index))
               (before-journal (my/workflow-test-file-text my/workflow-journal-file)))
          (should-error (my/work-start "Bad\ntitle" workspace-two "beta" "beta")
                        :type 'user-error)
          (should-error (my/work-start "Valid" workspace-two "bad\nkey" "beta")
                        :type 'user-error)
          (should-error (my/work-log 'progress "Bad\nlog") :type 'user-error)
          (should-error (my/work-project-log "Bad\rlog") :type 'user-error)
          (should (equal (my/workflow-test-file-text index) before-project))
          (should (equal (my/workflow-test-file-text my/workflow-journal-file)
                         before-journal))
          (with-current-buffer (find-file-noselect my/workflow-journal-file)
            (org-mode)
            (my/workflow-work-log-heading (current-time))
            (let ((level (org-outline-level)))
              (org-end-of-subtree t)
              (insert "\n" (make-string level ?*) " Work log\n"))
            (save-buffer))
          (setq before-journal (my/workflow-test-file-text my/workflow-journal-file))
          (should-error (my/work-log 'progress "Cannot append") :type 'user-error)
          (should (equal (my/workflow-test-file-text my/workflow-journal-file)
                         before-journal))
          (should (equal (plist-get task :id) (my/tab-current-property 'my/work-task-id))))))))

(ert-deftest my/workflow-draft-selection-filtering-and-finalize ()
  (my/workflow-test-with-storage
    (my/workflow-test-with-tabs
      (cl-letf (((symbol-function 'my/workflow-open-task) (lambda (task) task))
                ((symbol-function 'y-or-n-p) (lambda (&rest _arguments) t)))
        (let* ((first (my/work-start "First task" workspace "alpha" "first"))
               (second (my/work-start "Second task" workspace-two "alpha" "second"))
               (index (my/workflow-project-index-file "alpha"))
               (schema (my/workflow-project-schema (find-file-noselect index))))
          (my/workspace-select-or-create-tab workspace)
          (my/work-log 'progress "First task journal entry")
          (my/work-project-log "First task project log entry")
          (my/workspace-select-or-create-tab workspace-two)
          (my/work-log 'progress "Second task journal entry")
          (my/work-project-log "Second task project log entry")
          (with-current-buffer (find-file-noselect index)
            (save-excursion
              (goto-char (plist-get schema :docs))
              (org-end-of-subtree t)
              (insert "\n- [[file:relative-detail.md][Relative detail]]\n"
                      "- [[/ssh:build:/srv/private/detail.md][Remote detail]]\n")
              (save-buffer)))
          (let* ((schema (my/workflow-project-schema (find-file-noselect index)))
                 (items (my/workflow-draft-source-items second schema))
                 (sources
                  (seq-filter
                   (lambda (item)
                     (string-match-p
                      "\\`Docs 1:\\|\\`Project Log\\|Second task journal entry"
                      (plist-get item :label)))
                   items)))
            (should-not
             (seq-find
              (lambda (item)
                (string-match-p "First task" (plist-get item :label)))
              items))
            (my/work-draft-update sources))
          (let ((text (with-current-buffer "*Work Update Draft*" (buffer-string))))
            (should (string-match-p "Relative detail" text))
            (should-not (string-match-p "Remote detail" text))
            (should-not (string-match-p "relative-detail.md\|/ssh:build:" text))
            (should (string-match-p "Second task journal entry" text))
            (should-not (string-match-p "First task journal entry" text))
            (should (string-match-p "Second task project log entry" text))
            (should-not (string-match-p "First task project log entry" text))
            (should (< (string-match "Changed" text)
                       (string-match "Current status or blocker" text)
                       (string-match "Evidence" text)
                       (string-match "Next step" text))))
          (let (prompt candidates)
            (cl-letf (((symbol-function 'completing-read-multiple)
                       (lambda (selection-prompt collection &rest _arguments)
                         (setq prompt selection-prompt
                               candidates collection)
                         (list (seq-find
                                (lambda (candidate)
                                  (string-prefix-p "Docs 1:" candidate))
                                collection)))))
              (call-interactively #'my/work-draft-update))
            (should (equal prompt "Include sources: "))
            (should (member "Task text" candidates))
            (should (seq-find (lambda (candidate)
                                (string-prefix-p "Project Log 1:" candidate))
                              candidates))
            (should-not (seq-find (lambda (candidate)
                                    (string-match-p "First task" candidate))
                                  candidates))
            (with-current-buffer "*Work Update Draft*"
              (should (string-match-p "Relative detail" (buffer-string)))
              (should-not (string-match-p "Remote detail\|Second task journal entry"
                                          (buffer-string)))
              (goto-char (point-max))
              (insert "\n/tmp/added-after-review")
              (let (copied confirmation)
                (cl-letf (((symbol-function 'y-or-n-p)
                           (lambda (confirmation-prompt)
                             (setq confirmation confirmation-prompt)
                             nil))
                          ((symbol-function 'kill-new)
                           (lambda (text &rest _arguments) (setq copied text))))
                  (should-error (my/work-draft-finalize) :type 'user-error))
                (should-not copied)
                (should (string-match-p "current draft" confirmation))))
          (should (equal (my/workflow-sanitize-draft-text
                          (concat "Prefix [[file:relative.org][Relative]] "
                                  "[[/ssh:build:/srv/a][Remote]] "
                                  "[[https://example.com][Public]]\n"
                                  "[[file:another.org][Another]]"))
                         "Prefix Relative Remote [[https://example.com][Public]]\nAnother"))
          (should (equal (plist-get second :id)
                         (my/tab-current-property 'my/work-task-id)))
          (should-not (equal (plist-get first :id) (plist-get second :id)))))))))

(provide 'my-workflow-test)

;;; my-workflow-test.el ends here
