;;; send-text-targets-test.el --- Focused text target tests -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)

(load (expand-file-name "init.el" (file-name-directory (or load-file-name buffer-file-name)))
      nil nil nil t)

(defmacro my/send-text-test-with-tabs (tabs &rest body)
  "Run BODY with TABS behind the public tab-bar accessors."
  (declare (indent 1) (debug (form body)))
  `(let ((,tabs ,tabs))
     (cl-letf (((symbol-function 'tab-bar-tabs)
                (lambda () (copy-tree ,tabs)))
               ((symbol-function 'tab-bar-tabs-set)
                (lambda (updated) (setq ,tabs updated))))
       ,@body)))

(defun my/send-text-test-current-target (tabs)
  "Return the saved target in the current entry of TABS."
  (let (result)
    (dolist (tab tabs)
      (when (eq (car tab) 'current-tab)
        (setq result (alist-get 'my/send-text-last-target (cdr tab)))))
    result))

(ert-deftest my/send-text-source-annotations-and-bindings ()
  (let* ((buffers (list (generate-new-buffer " *send-text-file*" )
                        (generate-new-buffer " *send-text-scratch*")
                        (generate-new-buffer " *send-text-generated*")
                        (generate-new-buffer " *send-text-special*")
                        (generate-new-buffer " *send-text-remote*")
                        (generate-new-buffer " *send-text-process*")))
         (source-process
          (make-pipe-process :name "send-text-source"
                             :buffer (nth 5 buffers)
                             :noquery t))
        sent)
    (unwind-protect
        (progn
          (should (eq (get-buffer-process (nth 5 buffers)) source-process))
          (dolist (buffer buffers)
            (with-current-buffer buffer
              (let ((buffer-read-only nil))
                (erase-buffer)
                (insert "outside: selected :outside"))
              (when (equal buffer (car buffers))
                (setq buffer-file-name "/tmp/send-text-source"))
              (when (equal buffer (nth 3 buffers))
                (special-mode)
                (setq buffer-read-only t))
              (when (equal buffer (nth 4 buffers))
                (setq default-directory "/ssh:example:/tmp/"))
              (goto-char (+ (point-min) 9))
              (set-mark (+ (point-min) 17))
              (activate-mark)
              (cl-letf (((symbol-function 'my/send-text-to-target)
                         (lambda (text) (push text sent))))
                (let ((transient-mark-mode t))
                  (my/send-region-or-buffer)))
              (should (equal (car sent) "selected"))
              (deactivate-mark)))
          (with-current-buffer (car buffers)
            (let ((buffer-read-only nil))
              (erase-buffer)
              (insert "hidden-before\nvisible\nhidden-after\n"))
            (goto-char (point-min))
            (forward-line 1)
            (let ((begin (point)))
              (forward-line 1)
              (narrow-to-region begin (point)))
            (deactivate-mark)
            (cl-letf (((symbol-function 'my/send-text-to-target)
                       (lambda (text) (setq sent (list text)))))
              (my/send-region-or-buffer))
            (should (equal (car sent) "visible\n"))
            (widen))
          (with-current-buffer (car buffers)
            (let ((buffer-read-only nil))
              (erase-buffer)
              (insert "one\ntwo\nthree\nfour\n"))
            (goto-char (point-min))
            (forward-line 1)
            (let ((begin (point)))
              (forward-line 2)
              (narrow-to-region begin (point))
              (setq my/annotations nil)
              (my/annotate-region (point-min) (point-max) "Check lines")
              (should (= (plist-get (car my/annotations) :start-line) 2))
              (should (= (plist-get (car my/annotations) :end-line) 3))
              (should (equal (plist-get (car my/annotations) :text) "two\nthree\n"))
              (widen)))
          (let ((queued (list (list :source "source"
                                    :start-line 4
                                    :end-line 5
                                    :mode 'text-mode
                                    :annotation "Review"
                                    :text "``` four ```` six ``````"))))
            (setq my/annotations queued)
            (cl-letf (((symbol-function 'my/send-text-to-target)
                       (lambda (_text) (user-error "Target failed"))))
              (should-error (my/annotate-send-all "") :type 'user-error))
            (should (eq my/annotations queued))
            (let (prompt)
              (cl-letf (((symbol-function 'my/send-text-to-target)
                         (lambda (text) (setq prompt text))))
                (my/annotate-send-all ""))
              (should (string-match-p
                       (regexp-quote "```````\n``` four ```` six ``````\n```````")
                       prompt))
              (should-not my/annotations)))
          (let ((tabs (list '(current-tab (name . "labels"))))
                classes
                require-matches
                (destination (generate-new-buffer " *send-text-labels*")))
            (unwind-protect
                (my/send-text-test-with-tabs tabs
                  (cl-letf (((symbol-function 'buffer-list)
                             (lambda () (list destination)))
                            ((symbol-function 'completing-read)
                             (lambda (_prompt collection _predicate require-match &rest _)
                               (push require-match require-matches)
                               (if classes
                                   (buffer-name destination)
                                 (setq classes collection)
                                 "Writable Emacs buffer (insert at point)")))
                            ((symbol-function 'my/send-text-deliver)
                             (lambda (_target _text _replay))))
                    (my/send-text-to-target "labels")))
              (kill-buffer destination))
            (should (equal classes
                           '("Durable zmx session"
                             "Ghostel buffer"
                             "Emacs process buffer (raw text)"
                             "Writable Emacs buffer (insert at point)")))
            (should (equal require-matches '(t t))))
          (should (eq (keymap-lookup my/leader-map "t r")
                      #'my/send-region-or-buffer-to-last-target))
          (should (eq (keymap-lookup my/leader-map "t R") #'my/send-region-or-buffer))
          (should (eq (keymap-lookup my/leader-map "t g")
                      #'my/create-ghostel-terminal-in-split))
          (should (eq (keymap-lookup my/leader-map "t z")
                      #'my/open-or-create-zmx-session-in-split))
          (should (eq (lookup-key evil-visual-state-map (kbd "C-c C-c"))
                      #'my/send-region-or-buffer))
          (should (eq (lookup-key evil-visual-state-map (kbd "C-c C-r"))
                      #'my/send-region-or-buffer-to-last-target)))
      (dolist (buffer buffers)
        (when (buffer-live-p buffer)
          (kill-buffer buffer)))
      (when (process-live-p source-process)
        (delete-process source-process)))))

(ert-deftest my/send-text-zmx-tab-state-and-replay ()
  (let ((tabs (list '(current-tab (name . "first"))
                    '(tab (name . "second"))))
        calls)
    (my/send-text-test-with-tabs tabs
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (_prompt _collection _predicate require-match &rest _)
                   (should require-match)
                   "Durable zmx session"))
                ((symbol-function 'term-sessions-read-existing-session-entry)
                 (lambda (_prompt)
                   (if (eq (caar tabs) 'current-tab)
                       '(:name "first-session" :directory "/tmp/first/")
                     '(:name "second-session" :directory "/tmp/second/"))))
                ((symbol-function 'term-sessions-send)
                 (lambda (name text)
                   (push (list default-directory name text) calls))))
        (my/send-text-to-target "first text")
        (should (equal (my/send-text-test-current-target tabs)
                       '(:type zmx :name "first-session" :directory "/tmp/first/")))
        (should (equal (car calls) '("/tmp/first/" "first-session" "first text\r")))
        (setcar (car tabs) 'tab)
        (setcar (cadr tabs) 'current-tab)
        (my/send-text-to-target "second text")
        (should (equal (my/send-text-test-current-target tabs)
                       '(:type zmx :name "second-session" :directory "/tmp/second/")))
        (setf (alist-get 'name (cadr tabs)) "renamed-second")
        (setq tabs (list (cadr tabs) (car tabs)))
        (should (equal (my/send-text-test-current-target tabs)
                       '(:type zmx :name "second-session" :directory "/tmp/second/")))
        (let ((closed (car tabs)))
          (setcar closed 'tab)
          (setq tabs (append tabs (list '(current-tab (name . "new")))))
          (should-error (my/send-text-send-to-last-target "new") :type 'user-error)
          (setq tabs (delq closed tabs))
          (setq tabs (append tabs (list closed)))
          (setcar (cadr tabs) 'tab)
          (setcar closed 'current-tab)
          (my/send-text-send-to-last-target "restored")
          (should (equal (car calls)
                         '("/tmp/second/" "second-session" "restored\r"))))
        (let ((target (my/send-text-test-current-target tabs)))
          (cl-letf (((symbol-function 'term-sessions-send)
                     (lambda (_name _text) (user-error "zmx unavailable"))))
            (should-error (my/send-text-send-to-last-target "retry") :type 'user-error))
          (should (equal (my/send-text-test-current-target tabs) target))
          (cl-letf (((symbol-function 'term-sessions-read-existing-session-entry)
                     (lambda (_prompt) (user-error "selection failed"))))
            (should-error (my/send-text-to-target "new target") :type 'user-error))
          (should (equal (my/send-text-test-current-target tabs) target)))))))

(ert-deftest my/send-text-ghostel-process-and-buffer-transports ()
  (let ((tabs (list '(current-tab (name . "targets"))))
        (ghost (generate-new-buffer " *send-text-ghostel*"))
        (dead-ghost (generate-new-buffer " *send-text-dead-ghostel*"))
        (process-buffer (generate-new-buffer " *send-text-process*"))
        (writable (generate-new-buffer " *send-text-writable*")))
    (unwind-protect
        (my/send-text-test-with-tabs tabs
          (let ((ghostel-buffers (list ghost dead-ghost))
                (live-ghostel-buffers (list ghost))
                events
                required)
            (let ((real-require (symbol-function 'require)))
              (cl-letf (((symbol-function 'require)
                         (lambda (feature &optional filename noerror)
                           (if (eq feature 'ghostel)
                               (progn (setq required t) feature)
                             (funcall real-require feature filename noerror))))
                        ((symbol-function 'ghostel-buffer-list)
                         (lambda () ghostel-buffers))
                        ((symbol-function 'ghostel-buffer-live-p)
                         (lambda (buffer) (memq buffer live-ghostel-buffers)))
                        ((symbol-function 'ghostel-paste-string)
                         (lambda (text) (push (list 'paste text (current-buffer)) events)))
                        ((symbol-function 'ghostel-send-key)
                         (lambda (key) (push (list 'key key (current-buffer)) events)))
                        ((symbol-function 'completing-read)
                         (lambda (prompt collection _predicate require-match &rest _)
                           (should require-match)
                           (if (equal prompt "Target class: ")
                               "Ghostel buffer"
                             (progn
                               (should (equal collection (list (cons (buffer-name ghost) ghost))))
                               (buffer-name ghost))))))
                (my/send-text-to-target "ghost text")
                (should required)
                (should (equal (nreverse events)
                               (list (list 'paste "ghost text" ghost)
                                     (list 'key "return" ghost))))
                (let ((replacement (generate-new-buffer (buffer-name ghost))))
                  (kill-buffer ghost)
                  (setq ghostel-buffers (list replacement))
                  (setq live-ghostel-buffers (list replacement))
                  (should-error (my/send-text-send-to-last-target "stale") :type 'user-error)
                  (should-not (my/send-text-test-current-target tabs))
                  (kill-buffer replacement))
                (let ((prior '(:type zmx :name "prior" :directory "/tmp/prior/"))
                      (racing (generate-new-buffer " *send-text-racing*")))
                  (my/send-text-save-last-target prior)
                  (setq ghostel-buffers (list racing))
                  (setq live-ghostel-buffers (list racing))
                  (cl-letf (((symbol-function 'completing-read)
                             (lambda (prompt _collection _predicate _require-match &rest _)
                               (if (equal prompt "Target class: ")
                                   "Ghostel buffer"
                                 (buffer-name racing))))
                            ((symbol-function 'ghostel-paste-string)
                             (lambda (_text) (user-error "Ghostel exited during paste"))))
                    (should-error (my/send-text-to-target "race") :type 'user-error))
                  (should (equal (my/send-text-test-current-target tabs) prior))
                  (kill-buffer racing))
                (let ((prior '(:type zmx :name "prior" :directory "/tmp/prior/"))
                      (racing (generate-new-buffer " *send-text-return-racing*")))
                  (my/send-text-save-last-target prior)
                  (setq ghostel-buffers (list racing))
                  (setq live-ghostel-buffers (list racing))
                  (cl-letf (((symbol-function 'completing-read)
                             (lambda (prompt _collection _predicate _require-match &rest _)
                               (if (equal prompt "Target class: ")
                                   "Ghostel buffer"
                                 (buffer-name racing))))
                            ((symbol-function 'ghostel-send-key)
                             (lambda (_key) (user-error "Ghostel exited before Return"))))
                    (should-error (my/send-text-to-target "return race") :type 'user-error))
                  (should (equal (my/send-text-test-current-target tabs) prior))
                  (kill-buffer racing))))))
          (let ((process 'original-process)
                (replacement 'replacement-process)
                association
                sent)
            (setq association process)
            (cl-letf (((symbol-function 'buffer-list)
                       (lambda () (list process-buffer)))
                      ((symbol-function 'get-buffer-process)
                       (lambda (buffer) (and (eq buffer process-buffer) association)))
                      ((symbol-function 'process-live-p)
                       (lambda (value) (memq value (list process replacement))))
                      ((symbol-function 'process-send-string)
                       (lambda (value text) (setq sent (list value text))))
                      ((symbol-function 'completing-read)
                       (lambda (prompt _collection _predicate require-match &rest _)
                         (should require-match)
                         (if (equal prompt "Target class: ")
                             "Emacs process buffer (raw text)"
                           (buffer-name process-buffer)))))
              (my/send-text-to-target "raw\ntext")
              (should (equal sent (list process "raw\ntext")))
              (setq association replacement)
              (should-error (my/send-text-send-to-last-target "stale") :type 'user-error)
              (should-not (my/send-text-test-current-target tabs))))
          (with-current-buffer writable
            (insert "before after")
            (goto-char (+ (point-min) 7)))
          (cl-letf (((symbol-function 'buffer-list)
                     (lambda () (list writable)))
                    ((symbol-function 'completing-read)
                     (lambda (prompt _collection _predicate require-match &rest _)
                       (should require-match)
                       (if (equal prompt "Target class: ")
                           "Writable Emacs buffer (insert at point)"
                         (buffer-name writable)))))
            (my/send-text-to-target "INSERT")
            (with-current-buffer writable
              (should (equal (buffer-string) "before INSERTafter"))
              (should (buffer-modified-p))
              (setq buffer-read-only t))
            (let ((target (my/send-text-test-current-target tabs)))
              (should-error (my/send-text-send-to-last-target "blocked") :type 'user-error)
              (should (equal (my/send-text-test-current-target tabs) target)))
            (with-current-buffer writable
              (setq buffer-read-only nil))
            (kill-buffer writable)
            (let ((replacement (generate-new-buffer " *send-text-writable*")))
              (cl-letf (((symbol-function 'buffer-list) (lambda () (list replacement))))
                (should-error (my/send-text-send-to-last-target "stale") :type 'user-error)
                (should-not (my/send-text-test-current-target tabs)))
              (kill-buffer replacement)))
      (dolist (buffer (list ghost dead-ghost process-buffer writable))
        (when (buffer-live-p buffer)
          (kill-buffer buffer))))))

(ert-deftest my/send-text-split-creation-contracts ()
  (let ((tabs (list '(current-tab (name . "splits"))))
        (directory temporary-file-directory)
        (ghost (generate-new-buffer " *send-text-created-ghostel*")))
    (unwind-protect
        (my/send-text-test-with-tabs tabs
          (let (events create-directory create-action)
            (let ((real-require (symbol-function 'require)))
              (cl-letf (((symbol-function 'require)
                         (lambda (feature &optional filename noerror)
                           (if (eq feature 'ghostel)
                               feature
                             (funcall real-require feature filename noerror))))
                        ((symbol-function 'read-string)
                         (lambda (_prompt &rest _) (push 'prompt events) "named-ghostel"))
                        ((symbol-function 'ghostel-create)
                         (lambda (name action)
                           (push (list 'create name) events)
                           (setq create-directory default-directory
                                 create-action action)
                           ghost))
                        ((symbol-function 'ghostel-buffer-live-p)
                         (lambda (buffer) (eq buffer ghost))))
                (let ((default-directory directory))
                  (call-interactively #'my/create-ghostel-terminal-in-split))))
            (should (equal (nreverse events)
                           '(prompt (create "named-ghostel"))))
            (should (equal create-directory directory))
            (should (equal create-action
                           '((display-buffer-in-direction)
                             (direction . right)
                             (window-width . 0.5))))
            (should (equal (my/send-text-test-current-target tabs)
                           (list :type 'ghostel :buffer ghost))))
          (let ((prior '(:type zmx :name "prior" :directory "/tmp/prior/")))
            (my/send-text-save-last-target prior)
            (let ((real-require (symbol-function 'require)))
              (cl-letf (((symbol-function 'require)
                         (lambda (feature &optional filename noerror)
                           (if (eq feature 'ghostel)
                               feature
                             (funcall real-require feature filename noerror))))
                        ((symbol-function 'ghostel-create)
                         (lambda (_name _action) ghost))
                        ((symbol-function 'ghostel-buffer-live-p)
                         (lambda (_buffer) nil)))
                (should-error (my/create-ghostel-terminal-in-split "dead") :type 'user-error)))
            (should (equal (my/send-text-test-current-target tabs) prior)))
          (let (events opened-name opened-command opened-directory opened-action)
            (cl-letf (((symbol-function 'read-string)
                       (lambda (_prompt &rest _)
                         (push 'prompt events)
                         (if (= (length events) 1) "named-zmx" "command")))
                      ((symbol-function 'term-sessions-open)
                       (lambda (name command)
                         (push 'open events)
                         (setq opened-name name
                               opened-command command
                               opened-directory default-directory
                               opened-action display-buffer-overriding-action))))
              (let ((current-prefix-arg t)
                    (default-directory directory))
                (call-interactively #'my/open-or-create-zmx-session-in-split)))
            (should (equal (nreverse events) '(prompt prompt open)))
            (should (equal opened-name (list :name "named-zmx" :directory directory)))
            (should (equal opened-command "command"))
            (should (equal opened-directory directory))
            (should (equal opened-action
                           '((display-buffer-in-direction)
                             (direction . right)
                             (window-width . 0.5))))
            (should (equal (my/send-text-test-current-target tabs)
                           (list :type 'zmx :name "named-zmx" :directory directory))))
          (let ((prior (my/send-text-test-current-target tabs)))
            (cl-letf (((symbol-function 'term-sessions-open)
                       (lambda (_name _command) (user-error "zmx creation failed"))))
              (should-error (my/open-or-create-zmx-session-in-split "failed") :type 'user-error))
            (should (equal (my/send-text-test-current-target tabs) prior))))
      (when (buffer-live-p ghost)
        (kill-buffer ghost)))))

;;; send-text-targets-test.el ends here
