;;; send-text-targets-test.el --- Focused text target tests -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)

(add-to-list 'load-path
             (file-name-directory (or load-file-name buffer-file-name)))
(require 'my-send-text)

(defmacro my/send-text-test-with-tabs (tabs &rest body)
  "Run BODY with TABS behind the public tab-bar accessors."
  (declare (indent 1) (debug (form body)))
  `(let ((,tabs ,tabs))
     (cl-letf (((symbol-function 'tab-bar-tabs)
                (lambda () (copy-tree ,tabs)))
               ((symbol-function 'tab-bar-tabs-set)
                (lambda (updated) (setq ,tabs updated))))
       ,@body)))

(defun my/send-text-test-current-target (tabs)
  "Return the saved target in the current entry of TABS."
  (let (result)
    (dolist (tab tabs)
      (when (eq (car tab) 'current-tab)
        (setq result (alist-get 'my/send-text-last-target (cdr tab)))))
    result))

(ert-deftest my/send-text-source-annotations-and-bindings ()
  (let* ((buffers (list (generate-new-buffer " *send-text-file*" )
                        (generate-new-buffer " *send-text-scratch*")
                        (generate-new-buffer " *send-text-generated*")
                        (generate-new-buffer " *send-text-special*")
                        (generate-new-buffer " *send-text-remote*")
                        (generate-new-buffer " *send-text-process*")))
         (source-process
          (make-pipe-process :name "send-text-source"
                             :buffer (nth 5 buffers)
                             :noquery t))
        sent)
    (unwind-protect
        (progn
          (should (eq (get-buffer-process (nth 5 buffers)) source-process))
          (dolist (buffer buffers)
            (with-current-buffer buffer
              (let ((buffer-read-only nil))
                (erase-buffer)
                (insert "outside: selected :outside"))
              (when (equal buffer (car buffers))
                (setq buffer-file-name "/tmp/send-text-source"))
              (when (equal buffer (nth 3 buffers))
                (special-mode)
                (setq buffer-read-only t))
              (when (equal buffer (nth 4 buffers))
                (setq default-directory "/ssh:example:/tmp/"))
              (goto-char (+ (point-min) 9))
              (set-mark (+ (point-min) 17))
              (activate-mark)
              (cl-letf (((symbol-function 'my/send-text-to-target)
                         (lambda (text) (push text sent))))
                (let ((transient-mark-mode t))
                  (my/send-region-or-buffer)))
              (should (equal (car sent) "selected"))
              (deactivate-mark)))
          (with-current-buffer (car buffers)
            (let ((buffer-read-only nil))
              (erase-buffer)
              (insert "hidden-before\nvisible\nhidden-after\n"))
            (goto-char (point-min))
            (forward-line 1)
            (let ((begin (point)))
              (forward-line 1)
              (narrow-to-region begin (point)))
            (deactivate-mark)
            (cl-letf (((symbol-function 'my/send-text-to-target)
                       (lambda (text) (setq sent (list text)))))
              (my/send-region-or-buffer))
            (should (equal (car sent) "visible\n"))
            (widen))
          (with-current-buffer (car buffers)
            (let ((buffer-read-only nil))
              (erase-buffer)
              (insert "one\ntwo\nthree\nfour\n"))
            (goto-char (point-min))
            (forward-line 1)
            (let ((begin (point)))
              (forward-line 2)
              (narrow-to-region begin (point))
              (setq my/annotations nil)
              (my/annotate-region (point-min) (point-max) "Check lines")
              (should (= (plist-get (car my/annotations) :start-line) 2))
              (should (= (plist-get (car my/annotations) :end-line) 3))
              (should (equal (plist-get (car my/annotations) :text) "two\nthree\n"))
              (widen)))
          (let ((queued (list (list :source "source"
                                    :start-line 4
                                    :end-line 5
                                    :mode 'text-mode
                                    :annotation "Review"
                                    :text "``` four ```` six ``````"))))
            (setq my/annotations queued)
            (cl-letf (((symbol-function 'my/send-text-to-target)
                       (lambda (_text) (user-error "Target failed"))))
              (should-error (my/annotate-send-all "") :type 'user-error))
            (should (eq my/annotations queued))
            (let (prompt)
              (cl-letf (((symbol-function 'my/send-text-to-target)
                         (lambda (text) (setq prompt text))))
                (my/annotate-send-all ""))
              (should (string-match-p
                       (regexp-quote "```````\n``` four ```` six ``````\n```````")
                       prompt))
              (should-not my/annotations)))
          (let ((tabs (list '(current-tab (name . "labels"))))
                classes
                require-matches
                required
                (destination (generate-new-buffer " *send-text-labels*")))
            (unwind-protect
                (my/send-text-test-with-tabs tabs
                  (let ((real-require (symbol-function 'require)))
                    (cl-letf (((symbol-function 'require)
                               (lambda (feature &optional filename noerror)
                                 (if (eq feature 'ghostel)
                                     (progn (setq required t) feature)
                                   (funcall real-require feature filename noerror))))
                              ((symbol-function 'ghostel-buffer-list)
                               (lambda () nil))
                              ((symbol-function 'buffer-list)
                               (lambda () (list destination)))
                              ((symbol-function 'completing-read)
                               (lambda (prompt collection _predicate require-match &rest _)
                                 (push require-match require-matches)
                                 (if classes
                                   (buffer-name destination)
                                 (setq classes collection)
                                 (should (equal prompt "Target: "))
                                 "buffer")))
                            ((symbol-function 'my/send-text-deliver)
                             (lambda (_target _text _replay))))
                      (my/send-text-to-target "labels"))))
              (kill-buffer destination))
            (should (equal classes '("zmx" "buffer" "ghostty")))
            (should required)
            (should (equal require-matches '(t t)))))
      (dolist (buffer buffers)
        (when (buffer-live-p buffer)
          (kill-buffer buffer)))
      (when (process-live-p source-process)
        (delete-process source-process)))))

(ert-deftest my/send-text-hunk-annotations-review-and-delivery ()
  (let ((source (generate-new-buffer " *send-text-hunk-source*"))
        (hunk (generate-new-buffer " *send-text-hunk-patch*"))
        (existing-review (get-buffer my/annotations-buffer-name))
        (my/annotations nil)
        (my/annotation-next-id 0)
        failed-prompt
        sent-prompt)
    (unwind-protect
        (progn
          (with-current-buffer hunk
            (insert "diff --git a/source b/source\n"
                    "@@ -2 +2 @@\n"
                    "-beta\n"
                    "+BETA\n")
            (goto-char (point-min))
            (forward-line 1)
            (narrow-to-region (point) (point-max))
            (goto-char (point-min)))
          (with-current-buffer source
            (insert "alpha\nbeta\ngamma\n")
            (let ((begin (point-min)))
              (forward-line 1)
              (my/annotate-region begin (point) "Region note"))
            (cl-letf (((symbol-function 'diff-hl-mark-hunk)
                       (lambda ()
                         (goto-char (point-min))
                         (forward-line 1)
                         (push-mark (save-excursion
                                      (forward-line 1)
                                      (point))
                                    nil t)))
                      ((symbol-function 'diff-hl-show-hunk-buffer)
                       (lambda () (list hunk 2))))
              (my/annotate-current-hunk "Hunk note")))
          (let ((region (cadr my/annotations))
                (hunk-item (car my/annotations)))
            (should (= (plist-get region :id) 1))
            (should (= (plist-get hunk-item :id) 2))
            (should-not (plist-get region :patch))
            (should (equal (plist-get hunk-item :patch)
                           "@@ -2 +2 @@\n-beta\n+BETA\n"))
            (should (equal (plist-get hunk-item :text) "beta\n")))
          (let ((queued my/annotations))
            (cl-letf (((symbol-function 'my/send-text-to-target)
                       (lambda (prompt)
                         (setq failed-prompt prompt)
                         (user-error "Target failed"))))
              (should-error (my/annotate-send-all "") :type 'user-error))
            (should (eq my/annotations queued)))
          (should (< (string-match (regexp-quote "```diff\n@@ -2 +2 @@") failed-prompt)
                     (string-match "```\nbeta\n+```" failed-prompt)))
          (my/annotations-show)
          (let ((review (get-buffer my/annotations-buffer-name)))
            (with-current-buffer review
              (should (derived-mode-p 'my/annotations-mode))
              (should buffer-read-only)
              (goto-char (point-min))
              (should (= (plist-get (my/annotations-current-item) :id) 1))
              (my/annotations-next)
              (should (= (plist-get (my/annotations-current-item) :id) 2))
              (my/annotations-previous)
              (should (= (plist-get (my/annotations-current-item) :id) 1))
              (cl-letf (((symbol-function 'read-string)
                         (lambda (&rest _) "Edited region note")))
                (my/annotations-edit))
              (should (equal (plist-get (my/annotations-current-item) :annotation)
                             "Edited region note"))
              (my/annotations-refresh)
              (should (= (plist-get (my/annotations-current-item) :id) 1))
              (my/annotations-visit)
              (should (eq (current-buffer) source)))
            (with-current-buffer review
              (goto-char (point-min))
              (my/annotations-next)
              (my/annotations-delete))
            (should (= (length my/annotations) 1))
            (should-not sent-prompt)
            (with-current-buffer review
              (goto-char (point-min))
              (cl-letf (((symbol-function 'read-string)
                         (lambda (&rest _) "Final request"))
                        ((symbol-function 'my/send-text-to-target)
                         (lambda (prompt) (setq sent-prompt prompt))))
                (my/annotations-send)))
            (should (string-match-p "Final request" sent-prompt))
            (should (string-match-p "Edited region note" sent-prompt))
            (should-not my/annotations)))
      (when (buffer-live-p source)
        (kill-buffer source))
      (when (buffer-live-p hunk)
        (kill-buffer hunk))
      (unless existing-review
        (let ((review (get-buffer my/annotations-buffer-name)))
          (when (buffer-live-p review)
            (kill-buffer review)))))))

(ert-deftest my/send-text-zmx-tab-state-and-replay ()
  (let ((tabs (list '(current-tab (name . "first"))
                    '(tab (name . "second"))))
        calls
        selector-events)
    (my/send-text-test-with-tabs tabs
      (let ((real-require (symbol-function 'require)))
        (cl-letf (((symbol-function 'require)
                   (lambda (feature &optional filename noerror)
                     (if (eq feature 'term-sessions-list)
                         (progn
                           (push (list 'require feature) selector-events)
                           feature)
                       (if (eq feature 'ghostel)
                           (error "Ghostel should remain deferred for zmx")
                         (funcall real-require feature filename noerror)))))
                  ((symbol-function 'completing-read)
                   (lambda (prompt collection _predicate require-match &rest _)
                     (should require-match)
                     (pcase prompt
                       ("Target: "
                        (should (equal collection '("zmx" "buffer" "ghostty")))
                        "zmx")
                       ("zmx target: "
                        (should (equal collection '("existing" "create new")))
                        "existing")
                       (_ (error "Unexpected prompt: %S" prompt)))))
                  ((symbol-function 'term-sessions--read-existing-session-entry)
                   (lambda (prompt)
                     (push (list 'selector prompt) selector-events)
                     (if (eq (caar tabs) 'current-tab)
                         '(:name "first-session" :directory "/tmp/first/")
                       '(:name "second-session" :directory "/tmp/second/"))))
                  ((symbol-function 'term-sessions-send)
                   (lambda (name text)
                     (push (list default-directory name text) calls))))
          (my/send-text-to-target "first text")
          (should (equal (my/send-text-test-current-target tabs)
                         '(:type zmx :name "first-session" :directory "/tmp/first/")))
          (should (equal (car calls) '("/tmp/first/" "first-session" "first text\r")))
          (setcar (car tabs) 'tab)
          (setcar (cadr tabs) 'current-tab)
          (my/send-text-to-target "second text")
          (should (equal (my/send-text-test-current-target tabs)
                         '(:type zmx :name "second-session" :directory "/tmp/second/")))
          (should (equal (nreverse selector-events)
                         '((require term-sessions-list)
                           (selector "zmx session: ")
                           (require term-sessions-list)
                           (selector "zmx session: "))))
          (setf (alist-get 'name (cadr tabs)) "renamed-second")
          (setq tabs (list (cadr tabs) (car tabs)))
          (should (equal (my/send-text-test-current-target tabs)
                         '(:type zmx :name "second-session" :directory "/tmp/second/")))
          (let ((closed (car tabs))
                picker-text)
            (setcar closed 'tab)
            (setq tabs (append tabs (list '(current-tab (name . "new")))))
            (cl-letf (((symbol-function 'my/send-text-to-target)
                       (lambda (text) (setq picker-text text))))
              (my/send-text-send-to-last-target "new"))
            (should (equal picker-text "new"))
            (setq tabs (delq closed tabs))
            (setq tabs (append tabs (list closed)))
            (setcar (cadr tabs) 'tab)
            (setcar closed 'current-tab)
            (cl-letf (((symbol-function 'completing-read)
                       (lambda (&rest _) (error "Completion should not run"))))
              (my/send-text-send-to-last-target "restored"))
            (should (equal (car calls)
                           '("/tmp/second/" "second-session" "restored\r"))))
          (let ((target (my/send-text-test-current-target tabs)))
            (cl-letf (((symbol-function 'term-sessions-send)
                       (lambda (_name _text) (user-error "zmx unavailable"))))
              (should-error (my/send-text-send-to-last-target "retry") :type 'user-error))
            (should (equal (my/send-text-test-current-target tabs) target))
            (cl-letf (((symbol-function 'term-sessions--read-existing-session-entry)
                       (lambda (_prompt) (user-error "selection failed"))))
              (should-error (my/send-text-to-target "new target") :type 'user-error))
            (should (equal (my/send-text-test-current-target tabs) target))))
      (setq tabs (list '(current-tab (name . "creation"))))
      (let ((directory "/tmp/zmx-source/")
            (prior '(:type zmx :name "prior" :directory "/tmp/prior/"))
            events)
        (my/send-text-save-last-target prior)
        (cl-letf (((symbol-function 'completing-read)
                   (lambda (prompt collection _predicate require-match &rest _)
                     (should require-match)
                     (pcase prompt
                       ("Target: "
                        (should (equal collection '("zmx" "buffer" "ghostty")))
                        (setq default-directory "/tmp/changed-after-picker/")
                        "zmx")
                       ("zmx target: "
                        (should (equal collection '("existing" "create new")))
                        "create new")
                       (_ (error "Unexpected prompt: %S" prompt)))))
                  ((symbol-function 'read-string)
                   (lambda (prompt &rest _)
                     (should (equal prompt "zmx session name: "))
                     "created-session"))
                  ((symbol-function 'term-sessions-open)
                   (lambda (entry command)
                     (push (list 'open entry command default-directory
                                 display-buffer-overriding-action)
                           events)))
                  ((symbol-function 'term-sessions-send)
                   (lambda (name text)
                     (push (list 'send name text default-directory) events))))
          (let ((default-directory directory))
            (my/send-text-to-target "created text")))
        (should (equal (nreverse events)
                       (list
                        (list 'open
                              '(:name "created-session" :directory "/tmp/zmx-source/")
                              nil
                              "/tmp/zmx-source/"
                              my/send-text-right-split-action)
                        (list 'send "created-session" "created text\r" "/tmp/zmx-source/"))))
        (should (equal (my/send-text-test-current-target tabs)
                       '(:type zmx :name "created-session" :directory "/tmp/zmx-source/")))
        (dolist (failure '(open send))
          (my/send-text-save-last-target prior)
          (cl-letf (((symbol-function 'completing-read)
                     (lambda (prompt _collection _predicate require-match &rest _)
                       (should require-match)
                       (if (equal prompt "Target: ") "zmx" "create new")))
                    ((symbol-function 'read-string)
                     (lambda (&rest _) "failed-session"))
                    ((symbol-function 'term-sessions-open)
                     (lambda (&rest _)
                       (when (eq failure 'open)
                         (user-error "zmx creation failed"))))
                    ((symbol-function 'term-sessions-send)
                     (lambda (&rest _)
                       (when (eq failure 'send)
                         (user-error "zmx delivery failed")))))
            (should-error (my/send-text-to-target "failed text") :type 'user-error))
          (should (equal (my/send-text-test-current-target tabs) prior))))))))

(ert-deftest my/send-text-ghostel-process-and-buffer-transports ()
  (let ((tabs (list '(current-tab (name . "targets"))))
        (ghost (generate-new-buffer " *send-text-ghostel*"))
        (dead-ghost (generate-new-buffer " *send-text-dead-ghostel*"))
        (process-buffer (generate-new-buffer " *send-text-process*"))
        (writable (generate-new-buffer " *send-text-writable*"))
        (ambiguous (generate-new-buffer " *send-text-ambiguous*"))
        (created (generate-new-buffer " *send-text-created-ghostel*")))
    (unwind-protect
        (my/send-text-test-with-tabs tabs
          (dolist (buffer (list ghost dead-ghost))
            (with-current-buffer buffer
              (setq major-mode 'ghostel-mode
                    buffer-read-only t)))
          (with-current-buffer process-buffer
            (setq buffer-read-only t))
          (let ((candidate-buffers
                 (list ghost dead-ghost process-buffer writable ambiguous))
                (ghostel-buffers (list ghost dead-ghost))
                (ghost-process 'ghost-process)
                (dead-process 'dead-process)
                (process-only 'process-only)
                (ambiguous-process 'ambiguous-process)
                (replacement-process 'replacement-process)
                associations
                sent
                events
                required
                operation)
            (setq associations
                  (list (cons ghost ghost-process)
                        (cons dead-ghost dead-process)
                        (cons process-buffer process-only)
                        (cons ambiguous ambiguous-process)))
            (cl-letf (((symbol-function 'require)
                       (lambda (feature &rest _)
                         (if (eq feature 'ghostel)
                             (progn (setq required t) feature)
                           feature)))
                      ((symbol-function 'buffer-list)
                       (lambda () candidate-buffers))
                      ((symbol-function 'get-buffer-process)
                       (lambda (buffer)
                         (alist-get buffer associations nil nil #'eq)))
                      ((symbol-function 'ghostel-buffer-list)
                       (lambda () ghostel-buffers))
                      ((symbol-function 'process-live-p)
                       (lambda (process)
                         (memq process
                               (list ghost-process process-only ambiguous-process
                                     replacement-process))))
                      ((symbol-function 'process-send-string)
                       (lambda (process text) (setq sent (list process text))))
                      ((symbol-function 'ghostel-paste-string)
                       (lambda (text) (push (list 'paste text (current-buffer)) events)))
                      ((symbol-function 'ghostel-send-key)
                       (lambda (key) (push (list 'key key (current-buffer)) events)))
                      ((symbol-function 'completing-read)
                       (lambda (prompt collection _predicate require-match &rest _)
                         (should require-match)
                         (pcase prompt
                           ("Target: "
                            (should (equal collection '("zmx" "buffer" "ghostty")))
                            "buffer")
                           ("Buffer: "
                            (should
                             (equal collection
                                    (list
                                     (cons (buffer-name ghost)
                                           (list :type 'ghostel
                                                 :buffer ghost
                                                 :process ghost-process))
                                     (cons (buffer-name process-buffer)
                                           (list :type 'process
                                                 :buffer process-buffer
                                                 :process process-only))
                                     (cons (buffer-name writable)
                                           (list :type 'buffer :buffer writable))
                                     (cons (buffer-name ambiguous)
                                           (list :type 'process
                                                 :buffer ambiguous
                                                 :process ambiguous-process)))))
                            (buffer-name ghost))
                           (_ (error "Unexpected prompt: %S" prompt))))))
              (my/send-text-to-target "raw\ntext")
              (should required)
              (should (equal (my/send-text-test-current-target tabs)
                             (list :type 'ghostel
                                   :buffer ghost
                                   :process ghost-process)))
              (should (equal (nreverse events)
                             (list (list 'paste "raw\ntext" ghost)
                                   (list 'key "return" ghost))))
              (setf (alist-get ghost associations nil nil #'eq)
                    replacement-process)
              (should-error (my/send-text-send-to-last-target "stale") :type 'user-error)
              (should-not (my/send-text-test-current-target tabs)))
            (cl-letf (((symbol-function 'require)
                       (lambda (feature &rest _)
                         (if (eq feature 'ghostel)
                             feature
                           (error "Unexpected feature: %S" feature))))
                      ((symbol-function 'ghostel-buffer-list)
                       (lambda () nil))
                      ((symbol-function 'buffer-list)
                       (lambda () (list ambiguous)))
                      ((symbol-function 'get-buffer-process)
                       (lambda (buffer)
                         (and (eq buffer ambiguous) ambiguous-process)))
                      ((symbol-function 'process-live-p)
                       (lambda (process) (eq process ambiguous-process)))
                      ((symbol-function 'process-send-string)
                       (lambda (process text) (setq sent (list process text))))
                      ((symbol-function 'completing-read)
                       (lambda (prompt collection _predicate require-match &rest _)
                         (should require-match)
                         (pcase prompt
                           ("Target: " "buffer")
                           ("Buffer: " (buffer-name ambiguous))
                           ("Buffer operation: "
                            (setq operation collection)
                            "send raw text")
                           (_ (error "Unexpected prompt: %S" prompt))))))
              (my/send-text-to-target "ambiguous text")
              (should (equal operation '("send raw text" "insert at point")))
              (should (equal sent (list ambiguous-process "ambiguous text"))))
            (with-current-buffer writable
              (insert "before after")
              (goto-char (+ (point-min) 7)))
            (cl-letf (((symbol-function 'require)
                       (lambda (feature &rest _)
                         (if (eq feature 'ghostel)
                             feature
                           (error "Unexpected feature: %S" feature))))
                      ((symbol-function 'ghostel-buffer-list)
                       (lambda () nil))
                      ((symbol-function 'buffer-list)
                       (lambda () (list writable)))
                      ((symbol-function 'get-buffer-process)
                       (lambda (_buffer) nil))
                      ((symbol-function 'process-live-p)
                       (lambda (_process) nil))
                      ((symbol-function 'completing-read)
                       (lambda (prompt _collection _predicate require-match &rest _)
                         (should require-match)
                         (if (equal prompt "Target: ")
                             "buffer"
                           (buffer-name writable)))))
              (my/send-text-to-target "INSERT")
              (should (equal (my/send-text-test-current-target tabs)
                             (list :type 'buffer :buffer writable)))
              (with-current-buffer writable
                (should (equal (buffer-string) "before INSERTafter"))
                (setq buffer-read-only t))
              (let ((target (my/send-text-test-current-target tabs)))
                (should-error (my/send-text-send-to-last-target "blocked") :type 'user-error)
                (should (equal (my/send-text-test-current-target tabs) target)))))
          (with-current-buffer ghost
            (rename-buffer "create new" t))
          (with-current-buffer dead-ghost
            (rename-buffer "create new (existing)" t))
          (let ((ghostel-buffers (list ghost dead-ghost))
                (ghost-process 'ghost-process)
                (dead-process 'dead-process)
                associations
                events
                (selections '(("buffer: create new")
                              ("buffer: create new (existing)")))
                required)
            (setq associations (list (cons ghost ghost-process)
                                     (cons dead-ghost dead-process)))
            (cl-letf (((symbol-function 'require)
                       (lambda (feature &rest _)
                         (if (eq feature 'ghostel)
                             (progn (setq required t) feature)
                           (error "Unexpected feature: %S" feature))))
                      ((symbol-function 'ghostel-buffer-list)
                       (lambda () ghostel-buffers))
                      ((symbol-function 'get-buffer-process)
                       (lambda (buffer)
                         (alist-get buffer associations nil nil #'eq)))
                      ((symbol-function 'process-live-p)
                       (lambda (process) (memq process (list ghost-process dead-process))))
                      ((symbol-function 'ghostel-paste-string)
                       (lambda (text) (push (list 'paste text (current-buffer)) events)))
                      ((symbol-function 'ghostel-send-key)
                       (lambda (key) (push (list 'key key (current-buffer)) events)))
                      ((symbol-function 'completing-read)
                       (lambda (prompt collection _predicate require-match &rest _)
                         (should require-match)
                         (pcase prompt
                           ("Target: " "ghostty")
                           ("Ghostty: "
                            (should
                             (equal collection
                                    (list
                                     (cons "buffer: create new"
                                           (list :type 'ghostel
                                                 :buffer ghost
                                                 :process ghost-process))
                                     (cons "buffer: create new (existing)"
                                           (list :type 'ghostel
                                                 :buffer dead-ghost
                                                 :process dead-process))
                                     (cons "create new" 'create-new))))
                            (car (pop selections)))
                           (_ (error "Unexpected prompt: %S" prompt))))))
              (my/send-text-to-target "ghost text")
              (should required)
              (should (equal (my/send-text-test-current-target tabs)
                             (list :type 'ghostel
                                   :buffer ghost
                                   :process ghost-process)))
              (should (equal (reverse events)
                             (list (list 'paste "ghost text" ghost)
                                   (list 'key "return" ghost))))
              (my/send-text-to-target "second ghost text")
              (should (equal (my/send-text-test-current-target tabs)
                             (list :type 'ghostel
                                   :buffer dead-ghost
                                   :process dead-process)))
              (should (equal (reverse events)
                             (list (list 'paste "ghost text" ghost)
                                   (list 'key "return" ghost)
                                   (list 'paste "second ghost text" dead-ghost)
                                   (list 'key "return" dead-ghost))))
              (setf (alist-get dead-ghost associations nil nil #'eq) 'restarted-process)
              (should-error (my/send-text-send-to-last-target "stale") :type 'user-error)
              (should-not (my/send-text-test-current-target tabs))))
          (let ((directory "/tmp/ghostty-source/")
                (ghostel-buffers nil)
                (created-process 'created-process)
                events
                create-directory
                create-action)
            (cl-letf (((symbol-function 'require)
                       (lambda (feature &rest _)
                         (if (eq feature 'ghostel)
                             feature
                           (error "Unexpected feature: %S" feature))))
                      ((symbol-function 'ghostel-buffer-list)
                       (lambda () ghostel-buffers))
                      ((symbol-function 'get-buffer-process)
                       (lambda (buffer) (and (eq buffer created) created-process)))
                      ((symbol-function 'process-live-p)
                       (lambda (process) (eq process created-process)))
                      ((symbol-function 'ghostel-create)
                       (lambda (name action)
                         (push (list 'create name) events)
                         (setq create-directory default-directory
                               create-action action
                               ghostel-buffers (list created))
                         created))
                      ((symbol-function 'ghostel-paste-string)
                       (lambda (text) (push (list 'paste text (current-buffer)) events)))
                      ((symbol-function 'ghostel-send-key)
                       (lambda (key) (push (list 'key key (current-buffer)) events)))
                      ((symbol-function 'completing-read)
                       (lambda (prompt collection _predicate require-match &rest _)
                         (should require-match)
                         (pcase prompt
                           ("Target: "
                            (setq default-directory "/tmp/changed-after-picker/")
                            "ghostty")
                           ("Ghostty: "
                            (should (equal collection (list (cons "create new" 'create-new))))
                            "create new")
                           (_ (error "Unexpected prompt: %S" prompt)))))
                      ((symbol-function 'read-string)
                       (lambda (prompt &rest _)
                         (should (equal prompt "Ghostty buffer name (optional): "))
                         "created-ghostty")))
              (let ((default-directory directory))
                (my/send-text-to-target "created text"))
            (should (equal create-directory directory))
            (should (equal create-action my/send-text-right-split-action))
            (should (equal (nreverse events)
                           (list (list 'create "created-ghostty")
                                 (list 'paste "created text" created)
                                 (list 'key "return" created))))
            (should (equal (my/send-text-test-current-target tabs)
                           (list :type 'ghostel
                                 :buffer created
                                 :process created-process)))
            (dolist (failure '(create deliver))
              (let ((prior '(:type zmx :name "prior" :directory "/tmp/prior/")))
                (my/send-text-save-last-target prior)
                (setq ghostel-buffers nil)
                (cl-letf (((symbol-function 'completing-read)
                           (lambda (prompt _collection _predicate require-match &rest _)
                             (should require-match)
                             (if (equal prompt "Target: ") "ghostty" "create new")))
                          ((symbol-function 'read-string)
                           (lambda (&rest _) "failed-ghostty"))
                          ((symbol-function 'ghostel-create)
                           (lambda (_name _action)
                             (if (eq failure 'create)
                                 (user-error "Ghostty creation failed")
                               (setq ghostel-buffers (list created))
                               created)))
                          ((symbol-function 'ghostel-send-key)
                           (lambda (_key)
                             (when (eq failure 'deliver)
                               (user-error "Ghostty delivery failed")))))
                  (should-error (my/send-text-to-target "failed text") :type 'user-error))
                (should (equal (my/send-text-test-current-target tabs) prior)))))))
      (dolist (buffer (list ghost dead-ghost process-buffer writable ambiguous created))
        (when (buffer-live-p buffer)
          (kill-buffer buffer))))))

(ert-deftest my/send-text-split-creation-contracts ()
  (let ((tabs (list '(current-tab (name . "splits"))))
        (directory temporary-file-directory)
        (ghost (generate-new-buffer " *send-text-created-ghostel*"))
        (ghost-process 'created-ghostel-process))
    (unwind-protect
        (my/send-text-test-with-tabs tabs
          (let (events create-directory create-action)
            (let ((real-require (symbol-function 'require)))
              (cl-letf (((symbol-function 'require)
                         (lambda (feature &optional filename noerror)
                           (if (eq feature 'ghostel)
                               feature
                             (funcall real-require feature filename noerror))))
                        ((symbol-function 'read-string)
                         (lambda (_prompt &rest _) (push 'prompt events) "named-ghostel"))
                        ((symbol-function 'ghostel-create)
                         (lambda (name action)
                           (push (list 'create name) events)
                           (setq create-directory default-directory
                                 create-action action)
                           ghost))
                        ((symbol-function 'ghostel-buffer-list)
                         (lambda () (list ghost)))
                        ((symbol-function 'get-buffer-process)
                         (lambda (buffer) (and (eq buffer ghost) ghost-process)))
                        ((symbol-function 'process-live-p)
                         (lambda (process) (eq process ghost-process))))
                (let ((default-directory directory))
                  (call-interactively #'my/create-ghostel-terminal-in-split))))
            (should (equal (nreverse events)
                           '(prompt (create "named-ghostel"))))
            (should (equal create-directory directory))
            (should (equal create-action
                           '((display-buffer-in-direction)
                             (direction . right)
                             (window-width . 0.5))))
            (should (equal (my/send-text-test-current-target tabs)
                           (list :type 'ghostel
                                 :buffer ghost
                                 :process ghost-process))))
          (let ((prior '(:type zmx :name "prior" :directory "/tmp/prior/")))
            (my/send-text-save-last-target prior)
            (let ((real-require (symbol-function 'require)))
              (cl-letf (((symbol-function 'require)
                         (lambda (feature &optional filename noerror)
                           (if (eq feature 'ghostel)
                               feature
                             (funcall real-require feature filename noerror))))
                        ((symbol-function 'ghostel-create)
                         (lambda (_name _action) ghost))
                        ((symbol-function 'ghostel-buffer-list)
                         (lambda () (list ghost)))
                        ((symbol-function 'get-buffer-process)
                         (lambda (buffer) (and (eq buffer ghost) ghost-process)))
                        ((symbol-function 'process-live-p)
                         (lambda (_process) nil)))
                (should-error (my/create-ghostel-terminal-in-split "dead") :type 'user-error)))
            (should (equal (my/send-text-test-current-target tabs) prior)))
          (let (events opened-name opened-command opened-directory opened-action)
            (cl-letf (((symbol-function 'read-string)
                       (lambda (_prompt &rest _)
                         (push 'prompt events)
                         (if (= (length events) 1) "named-zmx" "command")))
                      ((symbol-function 'term-sessions-open)
                       (lambda (name command)
                         (push 'open events)
                         (setq opened-name name
                               opened-command command
                               opened-directory default-directory
                               opened-action display-buffer-overriding-action))))
              (let ((current-prefix-arg t)
                    (default-directory directory))
                (call-interactively #'my/open-or-create-zmx-session-in-split)))
            (should (equal (nreverse events) '(prompt prompt open)))
            (should (equal opened-name (list :name "named-zmx" :directory directory)))
            (should (equal opened-command "command"))
            (should (equal opened-directory directory))
            (should (equal opened-action
                           '((display-buffer-in-direction)
                             (direction . right)
                             (window-width . 0.5))))
            (should (equal (my/send-text-test-current-target tabs)
                           (list :type 'zmx :name "named-zmx" :directory directory))))
          (let ((prior (my/send-text-test-current-target tabs)))
            (cl-letf (((symbol-function 'term-sessions-open)
                       (lambda (_name _command) (user-error "zmx creation failed"))))
              (should-error (my/open-or-create-zmx-session-in-split "failed") :type 'user-error))
            (should (equal (my/send-text-test-current-target tabs) prior))))
      (when (buffer-live-p ghost)
        (kill-buffer ghost)))))

;;; send-text-targets-test.el ends here
